local p = game:GetService("Players").LocalPlayer
local Players = game:GetService("Players")
local U = game:GetService("UserInputService")
local R = game:GetService("RunService")
local TS = game:GetService("TeleportService")
local Workspace = game:GetService("Workspace")
local Camera = Workspace.CurrentCamera
local g = Instance.new("ScreenGui", p:WaitForChild("PlayerGui"))
g.ResetOnSpawn = false

local lang = "cn"
local L = {
    title = {"DS通用脚本中心 v2.5", "DS Universal Script Center v2.5"},
    info = {"本脚本由DeepSeek AI生成", "Generated by DeepSeek AI"},
    close = {"关闭", "Close"},
    walkspeed = {"移动加速", "Walk Speed"},
    flyspeed = {"飞行速度", "Fly Speed"},
    gravity = {"重力调节", "Gravity"},
    noclip = {"穿墙模式", "No Clip"},
    esp = {"玩家透视", "Player ESP"},
    esp_name = {"显示名字", "Show Name"},
    esp_hl = {"高亮玩家", "Highlight"},
    esp_line = {"绘制线", "Line"},
    fly_panel = {"开启飞行面板", "Open Fly Panel"},
    airwalk_panel = {"开启踏空面板", "Open Air Walk"},
    speed = {"速度倍率", "Speed Multiplier"},
    infjump = {"无限跳跃", "Infinite Jump"},
    server = {"服务器", "Server"},
    rejoin = {"重新加入", "Rejoin"},
    reset = {"重置人物", "Reset Character"},
    player_cat = {"人物", "Player"},
    fly_air_cat = {"飞行与踏空", "Fly & Air Walk"},
    combat_cat = {"战斗模块", "Combat Module"},
    combat_load = {"加载枪战脚本", "Load Gun Script"},
    combat_unload = {"卸载枪战脚本", "Unload Gun Script"},
    on_ = {"开", "ON"},
    off = {"关", "OFF"},
    fly_title = {"ds飞行", "ds Fly"},
    fly_start = {"开启飞行", "Start Fly"},
    fly_stop = {"关闭飞行", "Stop Fly"},
    fly_up = {"▲ 向上飞", "▲ Fly Up"},
    fly_down = {"▼ 向下飞", "▼ Fly Down"},
    air_title = {"ds踏空", "ds Air Walk"},
    air_start = {"开启踏空", "Start Air Walk"},
    air_stop = {"关闭踏空", "Stop Air Walk"},
}
local function T(key) return L[key] and L[key][lang == "cn" and 1 or 2] or key end
local langObjs = {}
local toggleBtns = {}
local function reg(o, k) table.insert(langObjs, {o = o, k = k}) o.Text = T(k) end
local function applyLang()
    for _, v in ipairs(langObjs) do v.o.Text = T(v.k) end
    for _, v in ipairs(toggleBtns) do
        v.btn.Text = T(v.state and "on_" or "off")
        v.btn.BackgroundColor3 = v.state and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35)
    end
    if combatLoaded and combatLangObjs then
        for _, v in ipairs(combatLangObjs) do
            if v.suffix then
                local num = v.obj.Text:match(": (.+)$")
                if num then v.obj.Text = T(v.key)..": "..num end
            else
                v.obj.Text = T(v.key)
            end
        end
    end
end
local function playSound()
    pcall(function()
        local s = Instance.new("Sound", g)
        s.SoundId = "rbxassetid://9119260689"
        s.Volume = 0.5 s:Play()
        game:GetService("Debris"):AddItem(s, 2)
    end)
end

-- Main window
local m = Instance.new("Frame", g)
m.BackgroundColor3 = Color3.fromRGB(24, 24, 24)
m.Size = UDim2.new(0, 300, 0, 0)
m.AutomaticSize = Enum.AutomaticSize.Y
m.Position = UDim2.new(0.5, -150, 0.1, 0)
m.BorderSizePixel = 0
Instance.new("UICorner", m).CornerRadius = UDim.new(0, 10)
local mainStroke = Instance.new("UIStroke", m)
mainStroke.Thickness = 2
mainStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border

local ml = Instance.new("UIListLayout", m)
ml.Padding = UDim.new(0, 8)
ml.HorizontalAlignment = Enum.HorizontalAlignment.Center
ml.SortOrder = Enum.SortOrder.LayoutOrder

-- Titlebar
local t = Instance.new("Frame", m)
t.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
t.Size = UDim2.new(1, -20, 0, 40)
t.BorderSizePixel = 0 t.LayoutOrder = 0
Instance.new("UICorner", t).CornerRadius = UDim.new(0, 8)
local dr = Instance.new("TextButton", t)
dr.BackgroundTransparency = 1 dr.Size = UDim2.new(1, 0, 1, 0) dr.Text = "" dr.ZIndex = 0
local ti = Instance.new("TextButton", t)
ti.TextColor3 = Color3.fromRGB(255, 255, 255) ti.BackgroundTransparency = 1
ti.Size = UDim2.new(0, 160, 1, 0) ti.Position = UDim2.new(0, 8, 0, 0)
ti.Font = Enum.Font.GothamBold ti.TextSize = 15 ti.TextXAlignment = Enum.TextXAlignment.Left ti.ZIndex = 2
reg(ti, "title")
local langBtn = Instance.new("TextButton", t) langBtn.Text = "EN"
langBtn.TextColor3 = Color3.fromRGB(255, 255, 255) langBtn.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
langBtn.Font = Enum.Font.GothamBold langBtn.TextSize = 12 langBtn.Size = UDim2.new(0, 28, 0, 28)
langBtn.Position = UDim2.new(1, -105, 0.5, -14) langBtn.ZIndex = 2 langBtn.BorderSizePixel = 0
Instance.new("UICorner", langBtn).CornerRadius = UDim.new(0, 4)
langBtn.MouseButton1Click:Connect(function()
    lang = lang == "cn" and "en" or "cn"
    langBtn.Text = lang == "cn" and "EN" or "中"
    applyLang()
end)
local minB = Instance.new("TextButton", t) minB.Text = "—"
minB.TextColor3 = Color3.fromRGB(255, 255, 255) minB.BackgroundColor3 = Color3.fromRGB(55, 55, 55)
minB.Font = Enum.Font.GothamBold minB.TextSize = 16 minB.Size = UDim2.new(0, 30, 0, 28)
minB.Position = UDim2.new(1, -70, 0.5, -14) minB.ZIndex = 2 minB.BorderSizePixel = 0
Instance.new("UICorner", minB).CornerRadius = UDim.new(0, 4)
local clsB = Instance.new("TextButton", t) clsB.Text = "✕"
clsB.TextColor3 = Color3.fromRGB(255, 255, 255) clsB.BackgroundColor3 = Color3.fromRGB(180, 50, 50)
clsB.Font = Enum.Font.GothamBold clsB.TextSize = 14 clsB.Size = UDim2.new(0, 30, 0, 28)
clsB.Position = UDim2.new(1, -34, 0.5, -14) clsB.ZIndex = 2 clsB.BorderSizePixel = 0
Instance.new("UICorner", clsB).CornerRadius = UDim.new(0, 4)

-- Info popup
local inf = Instance.new("Frame", t) inf.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
inf.Size = UDim2.new(0, 240, 0, 64) inf.Position = UDim2.new(0, 10, 1, 6) inf.Visible = false inf.ZIndex = 10
inf.BorderSizePixel = 0 Instance.new("UICorner", inf).CornerRadius = UDim.new(0, 6)
Instance.new("UIStroke", inf).Color = Color3.fromRGB(80, 80, 80)
local itx = Instance.new("TextLabel", inf) itx.TextColor3 = Color3.fromRGB(230, 230, 230) itx.BackgroundTransparency = 1
itx.Size = UDim2.new(1, -16, 0, 36) itx.Position = UDim2.new(0, 8, 0, 8) itx.Font = Enum.Font.GothamMedium
itx.TextSize = 14 itx.TextWrapped = true itx.ZIndex = 10 reg(itx, "info")
local cib = Instance.new("TextButton", inf) cib.TextColor3 = Color3.fromRGB(255, 255, 255) cib.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
cib.Font = Enum.Font.GothamBold cib.TextSize = 12 cib.Size = UDim2.new(0, 46, 0, 22) cib.Position = UDim2.new(1, -54, 1, -28)
cib.ZIndex = 11 cib.BorderSizePixel = 0 Instance.new("UICorner", cib).CornerRadius = UDim.new(0, 4) reg(cib, "close")
ti.MouseButton1Click:Connect(function() inf.Visible = not inf.Visible end)
cib.MouseButton1Click:Connect(function() inf.Visible = false end)
clsB.MouseButton1Click:Connect(function() g:Destroy() end)

-- Minimize button
local mRest = Instance.new("TextButton", g) mRest.Text = "DS" mRest.TextColor3 = Color3.fromRGB(255, 255, 255)
mRest.BackgroundColor3 = Color3.fromRGB(35, 35, 35) mRest.Font = Enum.Font.GothamBold mRest.TextSize = 14
mRest.Size = UDim2.new(0, 44, 0, 44) mRest.Position = UDim2.new(1, -54, 0.5, -22) mRest.Visible = false mRest.BorderSizePixel = 0
Instance.new("UICorner", mRest).CornerRadius = UDim.new(1, 0)
minB.MouseButton1Click:Connect(function() m.Visible = false; mRest.Visible = true end)
mRest.MouseButton1Click:Connect(function() m.Visible = true; mRest.Visible = false end)

-- Drag
local drag, ds, fs = false, nil, nil
dr.InputBegan:Connect(function(inp)
    if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then
        drag = true; ds = inp.Position; fs = m.Position
        inp.Changed:Connect(function()
            if inp.UserInputState == Enum.UserInputState.End then drag = false; ds = nil; fs = nil end
        end)
    end
end)
U.InputChanged:Connect(function(inp)
    if drag and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then
        local d = inp.Position - ds
        m.Position = UDim2.new(fs.X.Scale, fs.X.Offset + d.X, fs.Y.Scale, fs.Y.Offset + d.Y)
    end
end)

-- State
local s = {
    walkspeed = false, walkspeedValue = 50,
    flyspeed = true, flyspeedValue = 50,
    gravity = false, gravityValue = 1,
    noclip = false,
    esp = false, espShowName = true, espHighlight = true, espLine = false,
    speedMultiplier = false, speedMultiplierValue = 2,
    infiniteJump = false,
}

-- ESP
local eb, eh, ec = {}, {}, {}
local espLines = {}
local function uesp(pl) pcall(function()
    local ch = pl.Character if not ch or pl == p then return end
    if eb[pl] then eb[pl]:Destroy() end if eh[pl] then eh[pl]:Destroy() end eb[pl] = nil; eh[pl] = nil
    if s.esp and s.espShowName then
        local rp = ch:FindFirstChild("HumanoidRootPart")
        if rp then
            local b = Instance.new("BillboardGui", ch) b.Adornee = rp; b.Size = UDim2.new(0, 100, 0, 40); b.StudsOffset = Vector3.new(0, 3, 0); b.AlwaysOnTop = true
            local la = Instance.new("TextLabel", b) la.Size = UDim2.new(1, 0, 1, 0); la.BackgroundTransparency = 1; la.TextColor3 = Color3.fromRGB(0, 255, 0); la.TextStrokeTransparency = 0; la.TextStrokeColor3 = Color3.fromRGB(0, 0, 0); la.Text = pl.Name; la.Font = Enum.Font.GothamBold; la.TextSize = 14; la.TextScaled = true; la.BorderSizePixel = 0
            eb[pl] = b
        end
    end
    if s.esp and s.espHighlight then
        local hl = Instance.new("Highlight", ch) hl.FillColor = Color3.fromRGB(255, 255, 0); hl.OutlineColor = Color3.fromRGB(255, 255, 255); hl.FillTransparency = 0.5
        eh[pl] = hl
    end
end) end
local function aesp(pl) if pl == p then return end if ec[pl] then ec[pl]:Disconnect() end uesp(pl) ec[pl] = pl.CharacterAdded:Connect(function() uesp(pl) end) end
local function resp(pl)
    if ec[pl] then ec[pl]:Disconnect(); ec[pl] = nil end
    if eb[pl] then eb[pl]:Destroy(); eb[pl] = nil end
    if eh[pl] then eh[pl]:Destroy(); eh[pl] = nil end
    if espLines[pl] then espLines[pl]:Remove(); espLines[pl] = nil end
end
local function raesp() for _, v in ipairs(Players:GetPlayers()) do if v ~= p then uesp(v) end end end
Players.PlayerAdded:Connect(function(pl) if s.esp and pl ~= p then aesp(pl) end end)
Players.PlayerRemoving:Connect(resp)

-- UI row builder functions
local function adjRow(key, stateKey, def, ord, parent, noToggle)
    parent = parent or m
    local r = Instance.new("Frame", parent) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    r.Size = UDim2.new(1, -20, 0, 44) r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local lb = Instance.new("TextLabel", r) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1
    lb.Size = UDim2.new(0, 75, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left
    reg(lb, key)
    local vb = Instance.new("TextBox", r) vb.Text = tostring(def) vb.BackgroundColor3 = Color3.fromRGB(50, 50, 50) vb.TextColor3 = Color3.fromRGB(255, 255, 255) vb.Font = Enum.Font.GothamMedium vb.TextSize = 13
    vb.Size = UDim2.new(0, 48, 0, 26) vb.Position = UDim2.new(0, 90, 0.5, -13) vb.ClearTextOnFocus = false vb.BorderSizePixel = 0
    Instance.new("UICorner", vb).CornerRadius = UDim.new(0, 4)
    local function readValue()
        local n = tonumber(vb.Text) if n and n > 0 then s[stateKey .. "Value"] = n else vb.Text = tostring(s[stateKey .. "Value"]) end
    end
    vb:GetPropertyChangedSignal("Text"):Connect(function() local n = tonumber(vb.Text) if n and n > 0 then s[stateKey .. "Value"] = n end end)
    vb.FocusLost:Connect(readValue)
    if not noToggle then
        local tb = Instance.new("TextButton", r) tb.BackgroundColor3 = Color3.fromRGB(180, 35, 35) tb.TextColor3 = Color3.fromRGB(255, 255, 255) tb.Font = Enum.Font.GothamBold tb.TextSize = 13
        tb.Size = UDim2.new(0, 50, 0, 28) tb.Position = UDim2.new(1, -58, 0.5, -14) tb.BorderSizePixel = 0
        Instance.new("UICorner", tb).CornerRadius = UDim.new(0, 6)
        local state = false table.insert(toggleBtns, {btn = tb, state = state})
        local function uv(a) tb.Text = T(a and "on_" or "off") tb.BackgroundColor3 = a and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35) end
        tb.MouseButton1Click:Connect(function()
            readValue() s[stateKey] = not s[stateKey] state = s[stateKey] uv(state) playSound()
        end)
        s[stateKey .. "Value"] = def
    end
end

local function toggleRow(key, stateKey, ord, parent)
    parent = parent or m
    local r = Instance.new("Frame", parent) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    r.Size = UDim2.new(1, -20, 0, 44) r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local lb = Instance.new("TextLabel", r) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1
    lb.Size = UDim2.new(1, -70, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left
    reg(lb, key)
    local tb = Instance.new("TextButton", r) tb.BackgroundColor3 = Color3.fromRGB(180, 35, 35) tb.TextColor3 = Color3.fromRGB(255, 255, 255) tb.Font = Enum.Font.GothamBold tb.TextSize = 13
    tb.Size = UDim2.new(0, 50, 0, 28) tb.Position = UDim2.new(1, -58, 0.5, -14) tb.BorderSizePixel = 0
    Instance.new("UICorner", tb).CornerRadius = UDim.new(0, 6)
    local st = false table.insert(toggleBtns, {btn = tb, state = st})
    tb.MouseButton1Click:Connect(function()
        s[stateKey] = not s[stateKey] st = s[stateKey]
        tb.Text = T(st and "on_" or "off") tb.BackgroundColor3 = st and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35) playSound()
        if stateKey == "noclip" and not st and p.Character then for _, v in ipairs(p.Character:GetDescendants()) do if v:IsA("BasePart") then v.CanCollide = true end end end
    end)
end

-- Fly & Air Walk
local flyActive = false
local vert = 0
local flyW, flyRest, flyStroke

local function destroyFly()
    flyActive = false; vert = 0
    if flyW then flyW:Destroy(); flyW = nil end
    if flyRest then flyRest:Destroy(); flyRest = nil end flyStroke = nil
    local ch = p.Character if ch then local h = ch:FindFirstChildOfClass("Humanoid") if h then h.PlatformStand = false end end
end
local function showFly()
    if flyW then return end
    flyW = Instance.new("Frame", g) flyW.BackgroundColor3 = Color3.fromRGB(28, 28, 28) flyW.Size = UDim2.new(0, 210, 0, 210)
    flyW.Position = UDim2.new(0.5, -105, 0.3, 0) flyW.BorderSizePixel = 0 Instance.new("UICorner", flyW).CornerRadius = UDim.new(0, 8)
    flyStroke = Instance.new("UIStroke", flyW) flyStroke.Thickness = 2 flyStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    local ft = Instance.new("Frame", flyW) ft.BackgroundColor3 = Color3.fromRGB(38, 38, 38) ft.Size = UDim2.new(1, -16, 0, 36) ft.Position = UDim2.new(0, 8, 0, 6) ft.BorderSizePixel = 0
    Instance.new("UICorner", ft).CornerRadius = UDim.new(0, 6)
    local fti = Instance.new("TextLabel", ft) fti.TextColor3 = Color3.fromRGB(255, 255, 255) fti.BackgroundTransparency = 1 fti.Size = UDim2.new(1, -60, 1, 0) fti.Position = UDim2.new(0, 10, 0, 0) fti.Font = Enum.Font.GothamBold fti.TextSize = 16 fti.TextXAlignment = Enum.TextXAlignment.Left
    reg(fti, "fly_title")
    local fmin = Instance.new("TextButton", ft) fmin.Text = "—" fmin.TextColor3 = Color3.fromRGB(255, 255, 255) fmin.BackgroundColor3 = Color3.fromRGB(55, 55, 55) fmin.Font = Enum.Font.GothamBold fmin.TextSize = 16 fmin.Size = UDim2.new(0, 28, 0, 28) fmin.Position = UDim2.new(1, -58, 0.5, -14) fmin.BorderSizePixel = 0
    Instance.new("UICorner", fmin).CornerRadius = UDim.new(0, 4)
    local fcls = Instance.new("TextButton", ft) fcls.Text = "✕" fcls.TextColor3 = Color3.fromRGB(255, 255, 255) fcls.BackgroundColor3 = Color3.fromRGB(180, 50, 50) fcls.Font = Enum.Font.GothamBold fcls.TextSize = 14 fcls.Size = UDim2.new(0, 28, 0, 28) fcls.Position = UDim2.new(1, -28, 0.5, -14) fcls.BorderSizePixel = 0
    Instance.new("UICorner", fcls).CornerRadius = UDim.new(0, 4)
    local fdr = Instance.new("TextButton", ft) fdr.BackgroundTransparency = 1 fdr.Size = UDim2.new(1, 0, 1, 0) fdr.Text = "" fdr.ZIndex = 0
    local fdrg, fds, ffs = false, nil, nil fdr.InputBegan:Connect(function(inp) if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then fdrg = true; fds = inp.Position; ffs = flyW.Position inp.Changed:Connect(function() if inp.UserInputState == Enum.UserInputState.End then fdrg = false; fds = nil; ffs = nil end end) end end)
    U.InputChanged:Connect(function(inp) if fdrg and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then local d = inp.Position - fds flyW.Position = UDim2.new(ffs.X.Scale, ffs.X.Offset + d.X, ffs.Y.Scale, ffs.Y.Offset + d.Y) end end)
    local flyToggle = Instance.new("TextButton", flyW) flyToggle.TextColor3 = Color3.fromRGB(255, 255, 255) flyToggle.BackgroundColor3 = Color3.fromRGB(40, 130, 220) flyToggle.Font = Enum.Font.GothamBold flyToggle.TextSize = 14 flyToggle.Size = UDim2.new(1, -40, 0, 36) flyToggle.Position = UDim2.new(0, 20, 0, 54) flyToggle.BorderSizePixel = 0
    Instance.new("UICorner", flyToggle).CornerRadius = UDim.new(0, 6) reg(flyToggle, "fly_start")
    local up = Instance.new("TextButton", flyW) up.TextColor3 = Color3.fromRGB(255, 255, 255) up.BackgroundColor3 = Color3.fromRGB(40, 140, 40) up.Font = Enum.Font.GothamBold up.TextSize = 16 up.Size = UDim2.new(1, -40, 0, 40) up.Position = UDim2.new(0, 20, 0, 102) up.BorderSizePixel = 0
    Instance.new("UICorner", up).CornerRadius = UDim.new(0, 6) reg(up, "fly_up")
    local dn = Instance.new("TextButton", flyW) dn.TextColor3 = Color3.fromRGB(255, 255, 255) dn.BackgroundColor3 = Color3.fromRGB(40, 100, 180) dn.Font = Enum.Font.GothamBold dn.TextSize = 16 dn.Size = UDim2.new(1, -40, 0, 40) dn.Position = UDim2.new(0, 20, 0, 152) dn.BorderSizePixel = 0
    Instance.new("UICorner", dn).CornerRadius = UDim.new(0, 6) reg(dn, "fly_down")
    flyToggle.MouseButton1Click:Connect(function() flyActive = not flyActive flyToggle.Text = T(flyActive and "fly_stop" or "fly_start") flyToggle.BackgroundColor3 = flyActive and Color3.fromRGB(180, 50, 50) or Color3.fromRGB(40, 130, 220) playSound() if not flyActive then vert = 0 end end)
    up.MouseButton1Down:Connect(function() if flyActive then vert = 1 end end) up.MouseButton1Up:Connect(function() if vert == 1 then vert = 0 end end) up.MouseLeave:Connect(function() if vert == 1 then vert = 0 end end)
    dn.MouseButton1Down:Connect(function() if flyActive then vert = -1 end end) dn.MouseButton1Up:Connect(function() if vert == -1 then vert = 0 end end) dn.MouseLeave:Connect(function() if vert == -1 then vert = 0 end end)
    flyRest = Instance.new("TextButton", g) flyRest.Text = "飞" flyRest.TextColor3 = Color3.fromRGB(255, 255, 255) flyRest.BackgroundColor3 = Color3.fromRGB(40, 130, 220) flyRest.Font = Enum.Font.GothamBold flyRest.TextSize = 16 flyRest.Size = UDim2.new(0, 44, 0, 44) flyRest.Position = UDim2.new(1, -54, 0.5, 80) flyRest.Visible = false flyRest.BorderSizePixel = 0 Instance.new("UICorner", flyRest).CornerRadius = UDim.new(1, 0)
    fmin.MouseButton1Click:Connect(function() flyW.Visible = false; flyRest.Visible = true end) fcls.MouseButton1Click:Connect(function() destroyFly() end) flyRest.MouseButton1Click:Connect(function() flyW.Visible = true; flyRest.Visible = false end)
end

local airActive = false; local shouldFloat = false; local airBV, airHBConn, airHumanoid, airRoot = nil, nil, nil, nil
local airJumpConn, airStateConn, airCharConn = nil, nil, nil; local airW, airRest, airStroke = nil, nil, nil
local function updateAirFloat()
    if not airHumanoid or not airRoot then return end
    local inAir = (airHumanoid:GetState() == Enum.HumanoidStateType.Freefall or airHumanoid:GetState() == Enum.HumanoidStateType.Jumping)
    if airActive and shouldFloat and inAir then
        if not airBV then local bv = Instance.new("BodyVelocity") bv.MaxForce = Vector3.new(math.huge, math.huge, math.huge) bv.Velocity = Vector3.zero bv.Parent = airRoot airBV = bv end
        if not airHBConn then airHBConn = R.Heartbeat:Connect(function() if airBV and airBV.Parent and airHumanoid then local moveDir = airHumanoid.MoveDirection local speed = airHumanoid.WalkSpeed airBV.Velocity = Vector3.new(moveDir.X * speed, 0, moveDir.Z * speed) end end) end
    else if airBV then airBV:Destroy(); airBV = nil end if airHBConn then airHBConn:Disconnect(); airHBConn = nil end end
end
local function enableAirWalk() airActive = true if not airJumpConn then airJumpConn = U.JumpRequest:Connect(function() if not airActive or not airHumanoid or not airRoot then return end shouldFloat = true updateAirFloat() end) end end
local function disableAirWalk() airActive = false; shouldFloat = false if airBV then airBV:Destroy(); airBV = nil end if airHBConn then airHBConn:Disconnect(); airHBConn = nil end if airJumpConn then airJumpConn:Disconnect(); airJumpConn = nil end end
local function destroyAirWalk()
    disableAirWalk() if airStateConn then airStateConn:Disconnect(); airStateConn = nil end if airCharConn then airCharConn:Disconnect(); airCharConn = nil end
    if airW then airW:Destroy(); airW = nil end if airRest then airRest:Destroy(); airRest = nil end airStroke = nil; airHumanoid = nil; airRoot = nil
end
local function showAirWalk()
    if airW then return end
    local function onCharAdded(char) airHumanoid = char:WaitForChild("Humanoid") airRoot = char:WaitForChild("HumanoidRootPart") shouldFloat = false if airStateConn then airStateConn:Disconnect() end if airHumanoid then airStateConn = airHumanoid.StateChanged:Connect(function(_, newState) if newState == Enum.HumanoidStateType.Landed or newState == Enum.HumanoidStateType.Running then shouldFloat = false end updateAirFloat() end) end end
    if p.Character then onCharAdded(p.Character) end airCharConn = p.CharacterAdded:Connect(onCharAdded)
    airW = Instance.new("Frame", g) airW.BackgroundColor3 = Color3.fromRGB(28, 28, 28) airW.Size = UDim2.new(0, 180, 0, 120) airW.Position = UDim2.new(0.5, -90, 0.3, 0) airW.BorderSizePixel = 0 Instance.new("UICorner", airW).CornerRadius = UDim.new(0, 8)
    airStroke = Instance.new("UIStroke", airW) airStroke.Thickness = 2 airStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    local at = Instance.new("Frame", airW) at.BackgroundColor3 = Color3.fromRGB(38, 38, 38) at.Size = UDim2.new(1, -16, 0, 30) at.Position = UDim2.new(0, 8, 0, 5) at.BorderSizePixel = 0 Instance.new("UICorner", at).CornerRadius = UDim.new(0, 6)
    local ati = Instance.new("TextLabel", at) ati.TextColor3 = Color3.fromRGB(255, 255, 255) ati.BackgroundTransparency = 1 ati.Size = UDim2.new(1, -50, 1, 0) ati.Position = UDim2.new(0, 8, 0, 0) ati.Font = Enum.Font.GothamBold ati.TextSize = 14 ati.TextXAlignment = Enum.TextXAlignment.Left reg(ati, "air_title")
    local amin = Instance.new("TextButton", at) amin.Text = "—" amin.TextColor3 = Color3.fromRGB(255, 255, 255) amin.BackgroundColor3 = Color3.fromRGB(55, 55, 55) amin.Font = Enum.Font.GothamBold amin.TextSize = 14 amin.Size = UDim2.new(0, 24, 0, 24) amin.Position = UDim2.new(1, -50, 0.5, -12) amin.BorderSizePixel = 0 Instance.new("UICorner", amin).CornerRadius = UDim.new(0, 4)
    local acls = Instance.new("TextButton", at) acls.Text = "✕" acls.TextColor3 = Color3.fromRGB(255, 255, 255) acls.BackgroundColor3 = Color3.fromRGB(180, 50, 50) acls.Font = Enum.Font.GothamBold acls.TextSize = 12 acls.Size = UDim2.new(0, 24, 0, 24) acls.Position = UDim2.new(1, -24, 0.5, -12) acls.BorderSizePixel = 0 Instance.new("UICorner", acls).CornerRadius = UDim.new(0, 4)
    local adr = Instance.new("TextButton", at) adr.BackgroundTransparency = 1 adr.Size = UDim2.new(1, 0, 1, 0) adr.Text = "" adr.ZIndex = 0
    local adrag, ads, afs = false, nil, nil adr.InputBegan:Connect(function(inp) if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then adrag = true; ads = inp.Position; afs = airW.Position inp.Changed:Connect(function() if inp.UserInputState == Enum.UserInputState.End then adrag = false; ads = nil; afs = nil end end) end end)
    U.InputChanged:Connect(function(inp) if adrag and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then local d = inp.Position - ads airW.Position = UDim2.new(afs.X.Scale, afs.X.Offset + d.X, afs.Y.Scale, afs.Y.Offset + d.Y) end end)
    local airToggle = Instance.new("TextButton", airW) airToggle.TextColor3 = Color3.fromRGB(255, 255, 255) airToggle.BackgroundColor3 = Color3.fromRGB(180, 35, 35) airToggle.Font = Enum.Font.GothamBold airToggle.TextSize = 14 airToggle.Size = UDim2.new(1, -40, 0, 36) airToggle.Position = UDim2.new(0, 20, 0, 48) airToggle.BorderSizePixel = 0 Instance.new("UICorner", airToggle).CornerRadius = UDim.new(0, 6) reg(airToggle, "air_start")
    airToggle.MouseButton1Click:Connect(function() if airActive then disableAirWalk() airToggle.Text = T("air_start") airToggle.BackgroundColor3 = Color3.fromRGB(180, 35, 35) else enableAirWalk() airToggle.Text = T("air_stop") airToggle.BackgroundColor3 = Color3.fromRGB(40, 130, 40) end playSound() end)
    airRest = Instance.new("TextButton", g) airRest.Text = "空" airRest.TextColor3 = Color3.fromRGB(255, 255, 255) airRest.BackgroundColor3 = Color3.fromRGB(40, 130, 220) airRest.Font = Enum.Font.GothamBold airRest.TextSize = 14 airRest.Size = UDim2.new(0, 44, 0, 44) airRest.Position = UDim2.new(1, -54, 0.5, 130) airRest.Visible = false airRest.BorderSizePixel = 0 Instance.new("UICorner", airRest).CornerRadius = UDim.new(1, 0)
    amin.MouseButton1Click:Connect(function() airW.Visible = false; airRest.Visible = true end) acls.MouseButton1Click:Connect(function() destroyAirWalk() end) airRest.MouseButton1Click:Connect(function() airW.Visible = true; airRest.Visible = false end)
end

-- Category rows
local function categoryRow(titleKey, ord)
    local r = Instance.new("Frame", m) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 0) r.AutomaticSize = Enum.AutomaticSize.Y r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local rl = Instance.new("UIListLayout", r) rl.Padding = UDim.new(0, 4) rl.HorizontalAlignment = Enum.HorizontalAlignment.Center rl.SortOrder = Enum.SortOrder.LayoutOrder
    local top = Instance.new("Frame", r) top.BackgroundTransparency = 1 top.Size = UDim2.new(1, 0, 0, 44) top.LayoutOrder = 0
    local lb = Instance.new("TextLabel", top) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1 lb.Size = UDim2.new(1, -80, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left reg(lb, titleKey)
    local ex = Instance.new("TextButton", top) ex.Text = "▼" ex.BackgroundColor3 = Color3.fromRGB(55, 55, 55) ex.TextColor3 = Color3.fromRGB(255, 255, 255) ex.Font = Enum.Font.GothamBold ex.TextSize = 12 ex.Size = UDim2.new(0, 28, 0, 28) ex.Position = UDim2.new(1, -36, 0.5, -14) ex.BorderSizePixel = 0 Instance.new("UICorner", ex).CornerRadius = UDim.new(0, 4)
    local sf = Instance.new("Frame", r) sf.BackgroundTransparency = 1 sf.Size = UDim2.new(1, -16, 0, 0) sf.AutomaticSize = Enum.AutomaticSize.Y sf.Visible = false sf.LayoutOrder = 1
    local sl = Instance.new("UIListLayout", sf) sl.Padding = UDim.new(0, 4) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.SortOrder = Enum.SortOrder.LayoutOrder
    local exp = false
    ex.MouseButton1Click:Connect(function() exp = not exp; ex.Text = exp and "▲" or "▼"; sf.Visible = exp end)
    return sf
end

-- Player category
local playerCat = categoryRow("player_cat", 1)
adjRow("walkspeed", "walkspeed", 50, 1, playerCat)
toggleRow("infjump", "infiniteJump", 2, playerCat)
adjRow("gravity", "gravity", 1, 3, playerCat)
toggleRow("noclip", "noclip", 4, playerCat)
adjRow("speed", "speedMultiplier", 2.0, 5, playerCat)

-- Fly & Air Walk category
local flyAirCat = categoryRow("fly_air_cat", 2)
adjRow("flyspeed", "flyspeed", 50, 1, flyAirCat, true)
local flyBtnRow = function()
    local r = Instance.new("Frame", flyAirCat) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 44) r.LayoutOrder = 2 r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local btn = Instance.new("TextButton", r) btn.TextColor3 = Color3.fromRGB(255, 255, 255) btn.BackgroundColor3 = Color3.fromRGB(40, 130, 220) btn.Font = Enum.Font.GothamBold btn.TextSize = 14 btn.Size = UDim2.new(1, -16, 0, 34) btn.Position = UDim2.new(0, 8, 0.5, -17) btn.BorderSizePixel = 0
    Instance.new("UICorner", btn).CornerRadius = UDim.new(0, 6) reg(btn, "fly_panel")
    btn.MouseButton1Click:Connect(function() if flyW then destroyFly() else showFly() end end)
end
flyBtnRow()
local airBtnRow = function()
    local r = Instance.new("Frame", flyAirCat) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 44) r.LayoutOrder = 3 r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local btn = Instance.new("TextButton", r) btn.TextColor3 = Color3.fromRGB(255, 255, 255) btn.BackgroundColor3 = Color3.fromRGB(40, 130, 220) btn.Font = Enum.Font.GothamBold btn.TextSize = 14 btn.Size = UDim2.new(1, -16, 0, 34) btn.Position = UDim2.new(0, 8, 0.5, -17) btn.BorderSizePixel = 0
    Instance.new("UICorner", btn).CornerRadius = UDim.new(0, 6) reg(btn, "airwalk_panel")
    btn.MouseButton1Click:Connect(function() if airW then destroyAirWalk() else showAirWalk() end end)
end
airBtnRow()

-- ESP category
local function espRow(ord)
    local r = Instance.new("Frame", m) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 0) r.AutomaticSize = Enum.AutomaticSize.Y r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local rl = Instance.new("UIListLayout", r) rl.Padding = UDim.new(0, 4) rl.HorizontalAlignment = Enum.HorizontalAlignment.Center rl.SortOrder = Enum.SortOrder.LayoutOrder
    local top = Instance.new("Frame", r) top.BackgroundTransparency = 1 top.Size = UDim2.new(1, 0, 0, 44) top.LayoutOrder = 0
    local lb = Instance.new("TextLabel", top) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1 lb.Size = UDim2.new(0, 75, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left reg(lb, "esp")
    local ex = Instance.new("TextButton", top) ex.Text = "▼" ex.BackgroundColor3 = Color3.fromRGB(55, 55, 55) ex.TextColor3 = Color3.fromRGB(255, 255, 255) ex.Font = Enum.Font.GothamBold ex.TextSize = 12 ex.Size = UDim2.new(0, 28, 0, 28) ex.Position = UDim2.new(0, 92, 0.5, -14) ex.BorderSizePixel = 0 Instance.new("UICorner", ex).CornerRadius = UDim.new(0, 4)
    local tb = Instance.new("TextButton", top) tb.BackgroundColor3 = Color3.fromRGB(180, 35, 35) tb.TextColor3 = Color3.fromRGB(255, 255, 255) tb.Font = Enum.Font.GothamBold tb.TextSize = 13 tb.Size = UDim2.new(0, 50, 0, 28) tb.Position = UDim2.new(1, -58, 0.5, -14) tb.BorderSizePixel = 0 Instance.new("UICorner", tb).CornerRadius = UDim.new(0, 6) table.insert(toggleBtns, {btn = tb, state = false})
    local sf = Instance.new("Frame", r) sf.BackgroundTransparency = 1 sf.Size = UDim2.new(1, -16, 0, 0) sf.AutomaticSize = Enum.AutomaticSize.Y sf.Visible = false sf.LayoutOrder = 1
    local sl = Instance.new("UIListLayout", sf) sl.Padding = UDim.new(0, 4) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.SortOrder = Enum.SortOrder.LayoutOrder
    local function stoggle(nm, k, so)
        local sr = Instance.new("Frame", sf) sr.BackgroundColor3 = Color3.fromRGB(40, 40, 40) sr.Size = UDim2.new(1, 0, 0, 32) sr.LayoutOrder = so sr.BorderSizePixel = 0 Instance.new("UICorner", sr).CornerRadius = UDim.new(0, 4)
        local slb = Instance.new("TextLabel", sr) slb.TextColor3 = Color3.fromRGB(200, 200, 200) slb.BackgroundTransparency = 1 slb.Size = UDim2.new(1, -60, 1, 0) slb.Font = Enum.Font.GothamMedium slb.TextSize = 12 slb.TextXAlignment = Enum.TextXAlignment.Left reg(slb, nm)
        local stb = Instance.new("TextButton", sr) stb.BackgroundColor3 = Color3.fromRGB(150, 40, 40) stb.TextColor3 = Color3.fromRGB(255, 255, 255) stb.Font = Enum.Font.GothamBold stb.TextSize = 11 stb.Size = UDim2.new(0, 42, 0, 22) stb.Position = UDim2.new(1, -50, 0.5, -11) stb.BorderSizePixel = 0 Instance.new("UICorner", stb).CornerRadius = UDim.new(0, 4)
        local st = false table.insert(toggleBtns, {btn = stb, state = st})
        local function suv(v) stb.Text = T(v and "on_" or "off") stb.BackgroundColor3 = v and Color3.fromRGB(40, 130, 40) or Color3.fromRGB(150, 40, 40) end
        stb.MouseButton1Click:Connect(function() s[k] = not s[k]; st = s[k]; suv(st); playSound() if s.esp then raesp() end end) suv(s[k])
    end
    stoggle("esp_name", "espShowName", 1); stoggle("esp_hl", "espHighlight", 2); stoggle("esp_line", "espLine", 3)
    local exp = false ex.MouseButton1Click:Connect(function() exp = not exp; ex.Text = exp and "▲" or "▼"; sf.Visible = exp end)
    local function umv(a) tb.Text = T(a and "on_" or "off") tb.BackgroundColor3 = a and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35) end
    tb.MouseButton1Click:Connect(function() s.esp = not s.esp; umv(s.esp); playSound() if s.esp then for _, v in ipairs(Players:GetPlayers()) do if v ~= p then aesp(v) end end else for _, v in ipairs(Players:GetPlayers()) do resp(v) end end end)
end
espRow(3)

-- Server category
local function serverRow(ord)
    local r = Instance.new("Frame", m) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 0) r.AutomaticSize = Enum.AutomaticSize.Y r.LayoutOrder = ord r.BorderSizePixel = 0 Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local rl = Instance.new("UIListLayout", r) rl.Padding = UDim.new(0, 4) rl.HorizontalAlignment = Enum.HorizontalAlignment.Center rl.SortOrder = Enum.SortOrder.LayoutOrder
    local top = Instance.new("Frame", r) top.BackgroundTransparency = 1 top.Size = UDim2.new(1, 0, 0, 44) top.LayoutOrder = 0
    local lb = Instance.new("TextLabel", top) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1 lb.Size = UDim2.new(1, -80, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left reg(lb, "server")
    local ex = Instance.new("TextButton", top) ex.Text = "▼" ex.BackgroundColor3 = Color3.fromRGB(55, 55, 55) ex.TextColor3 = Color3.fromRGB(255, 255, 255) ex.Font = Enum.Font.GothamBold ex.TextSize = 12 ex.Size = UDim2.new(0, 28, 0, 28) ex.Position = UDim2.new(1, -36, 0.5, -14) ex.BorderSizePixel = 0 Instance.new("UICorner", ex).CornerRadius = UDim.new(0, 4)
    local sf = Instance.new("Frame", r) sf.BackgroundTransparency = 1 sf.Size = UDim2.new(1, -16, 0, 0) sf.AutomaticSize = Enum.AutomaticSize.Y sf.Visible = false sf.LayoutOrder = 1
    local sl = Instance.new("UIListLayout", sf) sl.Padding = UDim.new(0, 4) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.SortOrder = Enum.SortOrder.LayoutOrder
    local rejoinBtn = Instance.new("TextButton", sf) rejoinBtn.Size = UDim2.new(1, 0, 0, 32) rejoinBtn.BackgroundColor3 = Color3.fromRGB(40, 40, 40) rejoinBtn.TextColor3 = Color3.fromRGB(255, 255, 255) rejoinBtn.Font = Enum.Font.GothamBold rejoinBtn.TextSize = 13 rejoinBtn.BorderSizePixel = 0 Instance.new("UICorner", rejoinBtn).CornerRadius = UDim.new(0, 4) reg(rejoinBtn, "rejoin") rejoinBtn.MouseButton1Click:Connect(function() playSound() TS:Teleport(game.PlaceId, p) end)
    local resetBtn = Instance.new("TextButton", sf) resetBtn.Size = UDim2.new(1, 0, 0, 32) resetBtn.BackgroundColor3 = Color3.fromRGB(40, 40, 40) resetBtn.TextColor3 = Color3.fromRGB(255, 255, 255) resetBtn.Font = Enum.Font.GothamBold resetBtn.TextSize = 13 resetBtn.BorderSizePixel = 0 Instance.new("UICorner", resetBtn).CornerRadius = UDim.new(0, 4) reg(resetBtn, "reset") resetBtn.MouseButton1Click:Connect(function() playSound() if p.Character then p.Character:BreakJoints() end end)
    local exp = false ex.MouseButton1Click:Connect(function() exp = not exp; ex.Text = exp and "▲" or "▼"; sf.Visible = exp end)
end
serverRow(4)

-- ==================== 战斗模块分类 ====================
local combatLoaded = false
local combatGui = nil
local combatConnections = {}
local combatLangObjs = {}
local combatToggleBtns = {}

-- 战斗脚本的翻译
local combatL = {
    cn = {
        combat_title = "DS枪战中心",
        minimize = "—",
        restore = "⚡恢复",
        langBtn = "🌐 中",
        aim_section = "🎯 自瞄设置",
        aim_toggle = "开启自瞄",
        part_head = "锁定: 头部",
        part_body = "锁定: 身体",
        obst_check = "障碍检测",
        team_check = "队伍检测",
        smooth = "平滑度",
        radius = "范围半径",
        esp_section = "👁 绘制设置",
        name_esp = "名字透视",
        highlight_esp = "人物高亮",
        player_section = "🏃 人物增强",
        speed_toggle = "移动加速",
        speed_val = "加速值",
        noclip_toggle = "穿墙模式",
        fov_label = "📷 广角",
        fov_slider = "广角度数",
        hitbox_section = "📦 碰撞箱",
        hitbox_toggle = "修改碰撞箱",
        hitbox_mul = "碰撞倍数",
        adv_warning = "⚠ 高级设置有封禁风险!",
        fly_toggle = "飞行模式",
        fly_up_key = "上升: E",
        fly_down_key = "下降: Q",
        fly_speed = "飞行速度",
        adv_hitbox = "碰撞箱倍数",
        adv_speed = "移动速度(无限制)",
        adv_jump = "跳跃力度",
        adv_radius = "自瞄范围",
        close_adv = "关闭高级",
        on = "开",
        off = "关",
    },
    en = {
        combat_title = "DS Gun Center",
        minimize = "—",
        restore = "⚡ Restore",
        langBtn = "🌐 EN",
        aim_section = "🎯 Aimbot",
        aim_toggle = "Enable Aimbot",
        part_head = "Target: Head",
        part_body = "Target: Body",
        obst_check = "Wall Check",
        team_check = "Team Check",
        smooth = "Smoothness",
        radius = "Field Radius",
        esp_section = "👁 ESP",
        name_esp = "Name ESP",
        highlight_esp = "Highlight",
        player_section = "🏃 Movement",
        speed_toggle = "Speed Boost",
        speed_val = "Speed Value",
        noclip_toggle = "No Clip",
        fov_label = "📷 FOV",
        fov_slider = "FOV",
        hitbox_section = "📦 Hitbox",
        hitbox_toggle = "Expand Hitboxes",
        hitbox_mul = "Multiplier",
        adv_warning = "⚠ ADVANCED SETTINGS - BAN RISK!",
        fly_toggle = "Flight",
        fly_up_key = "Fly Up: E",
        fly_down_key = "Fly Down: Q",
        fly_speed = "Fly Speed",
        adv_hitbox = "Hitbox Mult.",
        adv_speed = "Speed (Unlim.)",
        adv_jump = "Jump Power",
        adv_radius = "Aimbot Radius",
        close_adv = "Close Advanced",
        on = "ON",
        off = "OFF",
    }
}
local function CT(key) return combatL[lang] and combatL[lang][key] or key end

local function updateCombatLang()
    if not combatLoaded or not combatLangObjs then return end
    for _, v in ipairs(combatLangObjs) do
        if v.suffix then
            local num = v.obj.Text:match(": (.+)$")
            if num then v.obj.Text = CT(v.key)..": "..num end
        else
            v.obj.Text = CT(v.key)
        end
    end
    for _, v in ipairs(combatToggleBtns) do
        v.btn.Text = v.state and CT("on") or CT("off")
    end
end

-- 卸载战斗脚本
local function unloadCombatScript()
    if not combatLoaded then return end
    combatLoaded = false
    for _, conn in ipairs(combatConnections) do
        pcall(function() conn:Disconnect() end)
    end
    combatConnections = {}
    if combatGui then
        combatGui:Destroy()
        combatGui = nil
    end
    combatLangObjs = {}
    combatToggleBtns = {}
    -- 恢复FOV
    Camera.FieldOfView = 70
    -- 清理战斗ESP
    for _, v in ipairs(Players:GetPlayers()) do
        if v ~= p then
            -- 触发原始ESP的resp来清理
            resp(v)
        end
    end
end

-- 加载战斗脚本
local function loadCombatScript()
    if combatLoaded then return end
    combatLoaded = true
    
    -- ===== 战斗脚本变量 =====
    local aimbotOn = false
    local aimPart = "Head"
    local obstCheck = true
    local teamCheck = true
    local smoothVal = 0.3
    local aimRadius = 150
    local nameEsp = false
    local highlightEsp = false
    local speedOn = false
    local speedVal = 30
    local noclipOn = false
    local fovVal = 70
    local hitboxOn = false
    local hitboxMul = 2
    local flyOn = false
    local flySpeed = 50
    local advHitboxMul = 10
    local advSpeed = 100
    local advJumpPower = 50
    local advRadius = 300
    
    local hlObjs, nameTags, origSizes, adornments = {}, {}, {}, {}
    local flyBV
    local flyKeys = {w=false,a=false,s=false,d=false,e=false,q=false}
    
    -- 战斗脚本UI辅助函数
    local combatUIOrder = 0
    local function CAddLabel(textKey)
        local lbl = Instance.new("TextLabel", combatScroll)
        lbl.Size = UDim2.new(1,-8,0,18)
        lbl.BackgroundTransparency = 1
        lbl.TextColor3 = Color3.fromRGB(255,255,0)
        lbl.Font = Enum.Font.SourceSansBold
        lbl.TextSize = 12
        lbl.TextXAlignment = Enum.TextXAlignment.Left
        lbl.Text = "  "..CT(textKey)
        lbl.LayoutOrder = combatUIOrder
        combatUIOrder = combatUIOrder + 1
        table.insert(combatLangObjs, {obj = lbl, key = textKey})
    end
    
    local function CAddToggle(textKey, default, callback)
        local f = Instance.new("Frame", combatScroll)
        f.Size = UDim2.new(1,-8,0,30)
        f.BackgroundColor3 = Color3.fromRGB(45,45,45)
        f.BorderSizePixel = 0
        f.LayoutOrder = combatUIOrder
        combatUIOrder = combatUIOrder + 1
        local lb = Instance.new("TextLabel", f)
        lb.Size = UDim2.new(0.6,0,1,0)
        lb.Position = UDim2.new(0.05,0,0,0)
        lb.BackgroundTransparency = 1
        lb.TextColor3 = Color3.fromRGB(200,200,200)
        lb.Font = Enum.Font.SourceSans
        lb.TextSize = 13
        lb.Text = CT(textKey)
        table.insert(combatLangObjs, {obj = lb, key = textKey})
        local btn = Instance.new("TextButton", f)
        btn.Size = UDim2.new(0,44,0,20)
        btn.Position = UDim2.new(0.75,0,0,5)
        btn.BorderSizePixel = 0
        btn.Text = ""
        local state = default
        local sLabel = Instance.new("TextLabel", btn)
        sLabel.Size = UDim2.new(1,0,1,0)
        sLabel.BackgroundTransparency = 1
        sLabel.TextColor3 = Color3.new(1,1,1)
        sLabel.Font = Enum.Font.SourceSansBold
        sLabel.TextSize = 11
        table.insert(combatToggleBtns, {btn = sLabel, state = state})
        local function upd()
            btn.BackgroundColor3 = state and Color3.fromRGB(40,200,40) or Color3.fromRGB(200,40,40)
            sLabel.Text = state and CT("on") or CT("off")
            if callback then callback(state) end
        end
        btn.MouseButton1Click:Connect(function() state = not state; upd() end)
        upd()
        return state
    end
    
    local function CAddSlider(textKey, min, max, default, callback)
        local f = Instance.new("Frame", combatScroll)
        f.Size = UDim2.new(1,-8,0,45)
        f.BackgroundColor3 = Color3.fromRGB(45,45,45)
        f.BorderSizePixel = 0
        f.LayoutOrder = combatUIOrder
        combatUIOrder = combatUIOrder + 1
        local lb = Instance.new("TextLabel", f)
        lb.Size = UDim2.new(0.4,0,0,20)
        lb.Position = UDim2.new(0.05,0,0,3)
        lb.BackgroundTransparency = 1
        lb.TextColor3 = Color3.fromRGB(200,200,200)
        lb.Font = Enum.Font.SourceSans
        lb.TextSize = 12
        lb.Text = CT(textKey)..": "..default
        table.insert(combatLangObjs, {obj = lb, key = textKey, suffix = true})
        local box = Instance.new("TextBox", f)
        box.Size = UDim2.new(0.5,0,0,20)
        box.Position = UDim2.new(0.5,0,0,22)
        box.BackgroundColor3 = Color3.fromRGB(70,70,70)
        box.TextColor3 = Color3.new(1,1,1)
        box.Font = Enum.Font.SourceSans
        box.TextSize = 12
        box.Text = tostring(default)
        box.FocusLost:Connect(function()
            local n = tonumber(box.Text)
            if n then n = math.clamp(n, min, max); box.Text = tostring(n); lb.Text = CT(textKey)..": "..n; if callback then callback(n) end
            else box.Text = tostring(default) end
        end)
        return tonumber(box.Text) or default
    end
    
    -- 战斗脚本功能函数
    local function CGetEnemies()
        local e = {}
        for _, pl in ipairs(Players:GetPlayers()) do
            if pl ~= p and pl.Character and pl.Character:FindFirstChild("Humanoid") and pl.Character.Humanoid.Health > 0 then
                if teamCheck and pl.Team and p.Team and pl.Team == p.Team then continue end
                table.insert(e, pl.Character)
            end
        end
        return e
    end
    
    local function AimbotUpdate()
        if not aimbotOn then return end
        local center = Vector2.new(Camera.ViewportSize.X/2, Camera.ViewportSize.Y/2)
        local closestTarget, minDist = nil, aimRadius + 1
        for _, char in ipairs(CGetEnemies()) do
            local part = char:FindFirstChild(aimPart)
            if part then
                local sp, onScreen = Camera:WorldToScreenPoint(part.Position)
                if onScreen then
                    local d = (Vector2.new(sp.X, sp.Y) - center).Magnitude
                    if d < minDist then
                        if obstCheck then
                            local rayParams = RaycastParams.new()
                            rayParams.FilterDescendantsInstances = {p.Character, char}
                            rayParams.FilterType = Enum.RaycastFilterType.Blacklist
                            local ray = Workspace:Raycast(Camera.CFrame.Position, (part.Position - Camera.CFrame.Position).Unit * 1000, rayParams)
                            if ray and ray.Instance and not ray.Instance:IsDescendantOf(char) then continue end
                        end
                        minDist = d
                        closestTarget = part.Position
                    end
                end
            end
        end
        if closestTarget then
            local goalCF = CFrame.new(Camera.CFrame.Position, closestTarget)
            Camera.CFrame = Camera.CFrame:Lerp(goalCF, smoothVal)
        end
    end
    
    local function RefreshESP()
        for _, v in pairs(hlObjs) do v:Destroy() end
        for _, v in pairs(nameTags) do v:Destroy() end
        hlObjs, nameTags = {}, {}
        if not (nameEsp or highlightEsp) then return end
        for _, char in ipairs(CGetEnemies()) do
            local plr = Players:GetPlayerFromCharacter(char)
            if plr then
                if nameEsp then
                    local bg = Instance.new("BillboardGui", char)
                    bg.Adornee = char:WaitForChild("Head", 5)
                    bg.Size = UDim2.new(0,100,0,30)
                    bg.StudsOffset = Vector3.new(0,3,0)
                    bg.AlwaysOnTop = true
                    local l = Instance.new("TextLabel", bg)
                    l.Size = UDim2.new(1,0,1,0)
                    l.BackgroundTransparency = 1
                    l.TextColor3 = Color3.new(1,1,1)
                    l.TextStrokeTransparency = 0
                    l.Font = Enum.Font.SourceSansBold
                    l.TextSize = 14
                    l.Text = plr.Name
                    nameTags[plr] = bg
                end
                if highlightEsp then
                    local hl = Instance.new("Highlight", combatGui)
                    hl.FillColor = Color3.fromRGB(255,100,100)
                    hl.OutlineColor = Color3.new(1,0,0)
                    hl.FillTransparency = 0.4
                    hl.OutlineTransparency = 0
                    hl.Adornee = char
                    hlObjs[plr] = hl
                end
            end
        end
    end
    
    local function UpdateHitboxes()for _, ads in pairs(adornments) do for _, a in ipairs(ads) do a:Destroy() end end
        adornments = {}
        for _, char in ipairs(CGetEnemies()) do
            local plr = Players:GetPlayerFromCharacter(char)
            if plr then
                if not origSizes[plr] then origSizes[plr] = {} end
                if not adornments[plr] then adornments[plr] = {} end
                for _, part in ipairs(char:GetDescendants()) do
                    if part:IsA("BasePart") then
                        if not origSizes[plr][part] then origSizes[plr][part] = part.Size end
                        local currentMul = hitboxOn and (hitboxMul or advHitboxMul) or 1
                        local ns = origSizes[plr][part] * currentMul
                        part.Size = ns
                        if hitboxOn then
                            local ad = Instance.new("BoxHandleAdornment", combatGui)
                            ad.Adornee = part
                            ad.Size = ns
                            ad.Transparency = 0.4
                            ad.Color3 = Color3.new(0,1,0)
                            ad.AlwaysOnTop = true
                            ad.ZIndex = 1
                            table.insert(adornments[plr], ad)
                        end
                    end
                end
            end
        end
        if not hitboxOn then
            for plr, parts in pairs(origSizes) do
                for part, sz in pairs(parts) do
                    if part and part.Parent then part.Size = sz end
                end
            end
            origSizes = {}
        end
    end
    
    local function ApplySpeed()
        local hum = p.Character and p.Character:FindFirstChild("Humanoid")
        if hum then hum.WalkSpeed = speedOn and (speedVal or advSpeed) or 16 end
    end
    
    local function SetupFly()
        if flyOn then
            local root = p.Character and p.Character:FindFirstChild("HumanoidRootPart")
            if root then
                if p.Character:FindFirstChild("Humanoid") then p.Character.Humanoid.PlatformStand = true end
                if not flyBV then
                    flyBV = Instance.new("BodyVelocity", root)
                    flyBV.MaxForce = Vector3.new(1e5,1e5,1e5)
                    flyBV.Velocity = Vector3.zero
                end
            end
        else
            if flyBV then flyBV:Destroy(); flyBV = nil end
            if p.Character and p.Character:FindFirstChild("Humanoid") then p.Character.Humanoid.PlatformStand = false end
        end
    end
    
    local function FlyUpdate()
        if not flyOn or not flyBV then return end
        local vel = Vector3.zero
        local cf = Camera.CFrame
        if flyKeys.w then vel = vel + cf.LookVector * flySpeed end
        if flyKeys.s then vel = vel - cf.LookVector * flySpeed end
        if flyKeys.a then vel = vel - cf.RightVector * flySpeed end
        if flyKeys.d then vel = vel + cf.RightVector * flySpeed end
        if flyKeys.e then vel = vel + Vector3.new(0,flySpeed,0) end
        if flyKeys.q then vel = vel - Vector3.new(0,flySpeed,0) end
        flyBV.Velocity = vel
    end
    
    -- 按键监听
    local keyBeganConn = U.InputBegan:Connect(function(inp)
        if not flyOn then return end
        if inp.KeyCode == Enum.KeyCode.W then flyKeys.w = true
        elseif inp.KeyCode == Enum.KeyCode.A then flyKeys.a = true
        elseif inp.KeyCode == Enum.KeyCode.S then flyKeys.s = true
        elseif inp.KeyCode == Enum.KeyCode.D then flyKeys.d = true
        elseif inp.KeyCode == Enum.KeyCode.E then flyKeys.e = true
        elseif inp.KeyCode == Enum.KeyCode.Q then flyKeys.q = true end
    end)
    table.insert(combatConnections, keyBeganConn)
    
    local keyEndConn = U.InputEnded:Connect(function(inp)
        if inp.KeyCode == Enum.KeyCode.W then flyKeys.w = false
        elseif inp.KeyCode == Enum.KeyCode.A then flyKeys.a = false
        elseif inp.KeyCode == Enum.KeyCode.S then flyKeys.s = false
        elseif inp.KeyCode == Enum.KeyCode.D then flyKeys.d = false
        elseif inp.KeyCode == Enum.KeyCode.E then flyKeys.e = false
        elseif inp.KeyCode == Enum.KeyCode.Q then flyKeys.q = false end
    end)
    table.insert(combatConnections, keyEndConn)
    
    -- 心跳
    local heartbeatConn = R.Heartbeat:Connect(function()
        AimbotUpdate()
        if noclipOn and p.Character then
            for _, part in ipairs(p.Character:GetDescendants()) do
                if part:IsA("BasePart") then part.CanCollide = false end
            end
        end
        if flyOn then FlyUpdate() end
    end)
    table.insert(combatConnections, heartbeatConn)
    
    -- 角色事件
    local charAddedConn = p.CharacterAdded:Connect(function()
        ApplySpeed()
        RefreshESP()
        UpdateHitboxes()
        if flyOn then SetupFly() end
    end)
    table.insert(combatConnections, charAddedConn)
    
    local playerAddedConn = Players.PlayerAdded:Connect(function(pl)
        pl.CharacterAdded:Connect(function() wait(0.3); RefreshESP(); UpdateHitboxes() end)
        if pl ~= p then wait(0.3); RefreshESP(); UpdateHitboxes() end
    end)
    table.insert(combatConnections, playerAddedConn)
    
    local playerRemovingConn = Players.PlayerRemoving:Connect(function(pl)
        if hlObjs[pl] then hlObjs[pl]:Destroy(); hlObjs[pl] = nil end
        if nameTags[pl] then nameTags[pl]:Destroy(); nameTags[pl] = nil end
        if adornments[pl] then for _, a in ipairs(adornments[pl]) do a:Destroy() end; adornments[pl] = nil end
        if origSizes[pl] then origSizes[pl] = nil end
    end)
    table.insert(combatConnections, playerRemovingConn)
    
    -- ===== 创建战斗GUI =====
    combatGui = Instance.new("ScreenGui", g)
    combatGui.Name = "DSCombatModule"
    
    local CombatMain = Instance.new("Frame", combatGui)
    CombatMain.Size = UDim2.new(0, 280, 0, 370)
    CombatMain.Position = UDim2.new(0.5, -140, 0.5, -185)
    CombatMain.BackgroundColor3 = Color3.fromRGB(30,30,30)
    CombatMain.BorderSizePixel = 0
    CombatMain.ClipsDescendants = true
    Instance.new("UIGradient", CombatMain).Color = ColorSequence.new{
        ColorSequenceKeypoint.new(0, Color3.fromRGB(40,40,40)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(20,20,20))
    }
    
    -- 标题栏
    local CombatTitleBar = Instance.new("Frame", CombatMain)
    CombatTitleBar.Size = UDim2.new(1,0,0,30)
    CombatTitleBar.BackgroundColor3 = Color3.new(0,0,0)
    CombatTitleBar.BackgroundTransparency = 0.5
    
    local CombatTitle = Instance.new("TextButton", CombatTitleBar)
    CombatTitle.Size = UDim2.new(0.4,0,1,0)
    CombatTitle.Position = UDim2.new(0.05,0,0,0)
    CombatTitle.BackgroundTransparency = 1
    CombatTitle.TextColor3 = Color3.new(1,1,1)
    CombatTitle.Font = Enum.Font.GothamBold
    CombatTitle.TextSize = 14
    CombatTitle.Text = CT("combat_title")
    table.insert(combatLangObjs, {obj = CombatTitle, key = "combat_title"})
    
    -- 关闭按钮
    local CombatCloseBtn = Instance.new("TextButton", CombatTitleBar)
    CombatCloseBtn.Size = UDim2.new(0,30,0,25)
    CombatCloseBtn.Position = UDim2.new(0.85,0,0,3)
    CombatCloseBtn.BackgroundColor3 = Color3.fromRGB(200,50,50)
    CombatCloseBtn.TextColor3 = Color3.new(1,1,1)
    CombatCloseBtn.Font = Enum.Font.SourceSansBold
    CombatCloseBtn.TextSize = 18
    CombatCloseBtn.Text = "X"
    CombatCloseBtn.MouseButton1Click:Connect(function() unloadCombatScript() end)
    
    -- 高级面板按钮(点击标题10次)
    local AdvPanel = Instance.new("Frame", combatGui)
    AdvPanel.Size = UDim2.new(0,260,0,220)
    AdvPanel.Position = UDim2.new(0.5,-130,0.5,-110)
    AdvPanel.BackgroundColor3 = Color3.fromRGB(20,20,20)
    AdvPanel.BorderSizePixel = 0
    AdvPanel.Visible = false
    AdvPanel.ZIndex = 500
    Instance.new("UIGradient", AdvPanel).Color = ColorSequence.new{
        ColorSequenceKeypoint.new(0, Color3.fromRGB(40,0,0)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(20,0,0))
    }
    
    local AdvTitle = Instance.new("TextLabel", AdvPanel)
    AdvTitle.Size = UDim2.new(1,0,0,24)
    AdvTitle.BackgroundColor3 = Color3.new(0,0,0)
    AdvTitle.TextColor3 = Color3.new(1,0,0)
    AdvTitle.Font = Enum.Font.GothamBold
    AdvTitle.TextSize = 13
    AdvTitle.Text = CT("adv_warning")
    AdvTitle.ZIndex = 2
    table.insert(combatLangObjs, {obj = AdvTitle, key = "adv_warning"})
    
    local AdvInner = Instance.new("ScrollingFrame", AdvPanel)
    AdvInner.Size = UDim2.new(1,-4,1,-50)
    AdvInner.Position = UDim2.new(0,2,0,26)
    AdvInner.BackgroundTransparency = 1
    AdvInner.BorderSizePixel = 0
    AdvInner.ScrollBarThickness = 3
    AdvInner.CanvasSize = UDim2.new(0,0,0,0)
    AdvInner.ZIndex = 2
    local AdvList = Instance.new("UIListLayout", AdvInner)
    AdvList.Padding = UDim.new(0,3)
    
    local closeAdvBtn = Instance.new("TextButton", AdvPanel)
    closeAdvBtn.Size = UDim2.new(0,80,0,20)
    closeAdvBtn.Position = UDim2.new(0.5,-40,1,-24)
    closeAdvBtn.BackgroundColor3 = Color3.fromRGB(150,0,0)
    closeAdvBtn.TextColor3 = Color3.new(1,1,1)
    closeAdvBtn.Font = Enum.Font.SourceSansBold
    closeAdvBtn.TextSize = 12
    closeAdvBtn.Text = CT("close_adv")
    closeAdvBtn.ZIndex = 3
    table.insert(combatLangObjs, {obj = closeAdvBtn, key = "close_adv"})
    closeAdvBtn.MouseButton1Click:Connect(function() AdvPanel.Visible = false end)
    
    local titleClickCount = 0
    CombatTitle.MouseButton1Click:Connect(function()
        titleClickCount = titleClickCount + 1
        if titleClickCount >= 10 then
            titleClickCount = 0
            AdvPanel.Visible = true
        end
    end)
    
    -- 高级面板元素
    local advOrder = 0
    local function CAddAdvToggle(textKey, default, callback)
        local f = Instance.new("Frame", AdvInner)
        f.Size = UDim2.new(1,-8,0,28)
        f.BackgroundColor3 = Color3.fromRGB(45,45,45)
        f.BorderSizePixel = 0
        f.LayoutOrder = advOrder; advOrder = advOrder + 1
        local lb = Instance.new("TextLabel", f)
        lb.Size = UDim2.new(0.6,0,1,0)
        lb.Position = UDim2.new(0.05,0,0,0)
        lb.BackgroundTransparency = 1
        lb.TextColor3 = Color3.fromRGB(200,200,200)
        lb.Font = Enum.Font.SourceSans
        lb.TextSize = 13
        lb.Text = CT(textKey)
        table.insert(combatLangObjs, {obj = lb, key = textKey})
        local btn = Instance.new("TextButton", f)
        btn.Size = UDim2.new(0,44,0,20)
        btn.Position = UDim2.new(0.75,0,0,4)
        btn.BorderSizePixel = 0
        btn.Text = ""
        local state = default
        local sLabel = Instance.new("TextLabel", btn)
        sLabel.Size = UDim2.new(1,0,1,0)
        sLabel.BackgroundTransparency = 1
        sLabel.TextColor3 = Color3.new(1,1,1)
        sLabel.Font = Enum.Font.SourceSansBold
        sLabel.TextSize = 11
        table.insert(combatToggleBtns, {btn = sLabel, state = state})
        local function upd()
            btn.BackgroundColor3 = state and Color3.fromRGB(40,200,40) or Color3.fromRGB(200,40,40)
            sLabel.Text = state and CT("on") or CT("off")
            if callback then callback(state) end
        end
        btn.MouseButton1Click:Connect(function() state = not state; upd() end)
        upd()
    end
    
    local function CAddAdvSlider(textKey, min, max, default, callback)
        local f = Instance.new("Frame", AdvInner)
        f.Size = UDim2.new(1,-8,0,42)
        f.BackgroundColor3 = Color3.fromRGB(45,45,45)
        f.BorderSizePixel = 0
        f.LayoutOrder = advOrder; advOrder = advOrder + 1
        local lb = Instance.new("TextLabel", f)
        lb.Size = UDim2.new(0.4,0,0,18)
        lb.Position = UDim2.new(0.05,0,0,2)
        lb.BackgroundTransparency = 1
        lb.TextColor3 = Color3.fromRGB(200,200,200)
        lb.Font = Enum.Font.SourceSans
        lb.TextSize = 12
        lb.Text = CT(textKey)..": "..default
        table.insert(combatLangObjs, {obj = lb, key = textKey, suffix = true})
        local box = Instance.new("TextBox", f)
        box.Size = UDim2.new(0.5,0,0,18)
        box.Position = UDim2.new(0.5,0,0,20)
        box.BackgroundColor3 = Color3.fromRGB(70,70,70)
        box.TextColor3 = Color3.new(1,1,1)
        box.Font = Enum.Font.SourceSans
        box.TextSize = 12
        box.Text = tostring(default)
        box.FocusLost:Connect(function()
            local n = tonumber(box.Text)
            if n then n = math.clamp(n, min, max); box.Text = tostring(n); lb.Text = CT(textKey)..": "..n; if callback then callback(n) end
            else box.Text = tostring(default) end
        end)
    end
    
    -- 高级面板内容
    CAddAdvToggle("fly_toggle", false, function(v) flyOn = v; SetupFly() end)
    CAddAdvSlider("fly_speed", 10, 500, 50, function(v) flySpeed = v end)
    CAddAdvSlider("adv_hitbox", 1, 100, 10, function(v) advHitboxMul = v; UpdateHitboxes() end)
    CAddAdvSlider("adv_speed", 1, 1000, 100, function(v) advSpeed = v; ApplySpeed() end)
    CAddAdvSlider("adv_jump", 0, 500, 50, function(v) advJumpPower = v; if p.Character and p.Character:FindFirstChild("Humanoid") then p.Character.Humanoid.JumpPower = v end end)
    CAddAdvSlider("adv_radius", 50, 2000, 300, function(v) advRadius = v end)
    
    -- 可滚动内容
    combatScroll = Instance.new("ScrollingFrame", CombatMain)
    combatScroll.Size = UDim2.new(1,-4,1,-34)
    combatScroll.Position = UDim2.new(0,2,0,32)
    combatScroll.BackgroundTransparency = 1
    combatScroll.BorderSizePixel = 0
    combatScroll.ScrollBarThickness = 3
    combatScroll.CanvasSize = UDim2.new(0,0,0,0)
    local combatList = Instance.new("UIListLayout", combatScroll)
    combatList.Padding = UDim.new(0,3)
    
    -- 构建UI
    CAddLabel("aim_section")
    local partBtn = Instance.new("TextButton", combatScroll)
    partBtn.Size = UDim2.new(1,-8,0,26)
    partBtn.BackgroundColor3 = Color3.fromRGB(70,70,70)
    partBtn.TextColor3 = Color3.new(1,1,1)
    partBtn.Font = Enum.Font.SourceSans
    partBtn.TextSize = 13
    partBtn.LayoutOrder = combatUIOrder; combatUIOrder = combatUIOrder + 1
    partBtn.Text = CT("part_head")
    table.insert(combatLangObjs, {obj = partBtn, key = "part_head"})
    local origPartBtn = partBtn
    partBtn.MouseButton1Click:Connect(function()
        aimPart = aimPart == "Head" and "HumanoidRootPart" or "Head"
        partBtn.Text = aimPart == "Head" and CT("part_head") or CT("part_body")
        -- 存储当前显示的状态用于语言切换
        partBtn._isHead = aimPart == "Head"
    end)
    partBtn._isHead = true
    
    CAddToggle("aim_toggle", false, function(v) aimbotOn = v end)
    CAddToggle("obst_check", true, function(v) obstCheck = v end)
    CAddToggle("team_check", true, function(v) teamCheck = v end)
    CAddSlider("smooth", 0.1, 1, 0.3, function(v) smoothVal = v end)
    CAddSlider("radius", 50, 400, 150, function(v) aimRadius = v end)
    
    CAddLabel("esp_section")
    CAddToggle("name_esp", false, function(v) nameEsp = v; RefreshESP() end)
    CAddToggle("highlight_esp", false, function(v) highlightEsp = v; RefreshESP() end)
    
    CAddLabel("player_section")
    CAddToggle("speed_toggle", false, function(v) speedOn = v; ApplySpeed() end)
    CAddSlider("speed_val", 20, 200, 30, function(v) speedVal = v; ApplySpeed() end)
    CAddToggle("noclip_toggle", false, function(v) noclipOn = v end)
    
    CAddLabel("fov_label")
    CAddSlider("fov_slider", 30, 150, 70, function(v) fovVal = v; Camera.FieldOfView = v end)
    
    CAddLabel("hitbox_section")
    CAddToggle("hitbox_toggle", false, function(v) hitboxOn = v; UpdateHitboxes() end)
    CAddSlider("hitbox_mul", 1.1, 5, 2, function(v) hitboxMul = v; UpdateHitboxes() end)
    
    -- 更新滚动大小
    combatScroll.CanvasSize = UDim2.new(0,0,0, combatList.AbsoluteContentSize.Y + 10)
    AdvInner.CanvasSize = UDim2.new(0,0,0, AdvList.AbsoluteContentSize.Y + 10)
    
    -- 初始化
    ApplySpeed()
    Camera.FieldOfView = fovVal
    if p.Character and p.Character:FindFirstChild("Humanoid") then
        p.Character.Humanoid.JumpPower = advJumpPower
    end
    RefreshESP()
end

-- 战斗模块分类UI
local combatCat = categoryRow("combat_cat", 5)
local combatBtnRow = function()
    local r = Instance.new("Frame", combatCat)
    r.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    r.Size = UDim2.new(1, -20, 0, 44)
    r.LayoutOrder = 1
    r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local btn = Instance.new("TextButton", r)
    btn.TextColor3 = Color3.fromRGB(255, 255, 255)
    btn.BackgroundColor3 = Color3.fromRGB(180, 50, 50)
    btn.Font = Enum.Font.GothamBold
    btn.TextSize = 14
    btn.Size = UDim2.new(1, -16, 0, 34)
    btn.Position = UDim2.new(0, 8, 0.5, -17)
    btn.BorderSizePixel = 0
    Instance.new("UICorner", btn).CornerRadius = UDim.new(0, 6)
    reg(btn, "combat_load")
    local loaded = false
    btn.MouseButton1Click:Connect(function()
        if combatLoaded then
            unloadCombatScript()
            btn.Text = T("combat_load")
            btn.BackgroundColor3 = Color3.fromRGB(180, 50, 50)
        else
            loadCombatScript()
            btn.Text = T("combat_unload")
            btn.BackgroundColor3 = Color3.fromRGB(40, 130, 40)
        end
        playSound()
    end)
end
combatBtnRow()

-- Infinite jump
U.JumpRequest:Connect(function()
    if not s.infiniteJump then return end
    local c = p.Character if c then local h = c:FindFirstChildOfClass("Humanoid") if h and h:GetState() ~= Enum.HumanoidStateType.Landed then h:ChangeState(Enum.HumanoidStateType.Jumping) end end
end)

local lh = nil local dws = 16 local hue = 0
R.Heartbeat:Connect(function(dt)
    hue = (hue + 60 * dt) % 360
    local color = Color3.fromHSV(hue / 360, 1, 1)
    mainStroke.Color = color
    if flyStroke then flyStroke.Color = color end
    if airStroke then airStroke.Color = color end
    ti.TextColor3 = color
    local c = p.Character local h = c and c:FindFirstChildOfClass("Humanoid") local r = c and c:FindFirstChild("HumanoidRootPart")
    if h then
        if h ~= lh then dws = h.WalkSpeed; lh = h end
        if s.walkspeed then h.WalkSpeed = math.max(1, s.walkspeedValue) else h.WalkSpeed = dws end
        if s.speedMultiplier then h.WalkSpeed = h.WalkSpeed * s.speedMultiplierValue end
    else lh = nil end
    if s.gravity then Workspace.Gravity = 196.2 * s.gravityValue else Workspace.Gravity = 196.2 end
    if c and s.noclip then for _, v in ipairs(c:GetDescendants()) do if v:IsA("BasePart") then v.CanCollide = false end end end
    if flyActive and r and h then
        h.PlatformStand = true
        local md = h.MoveDirection if md.Magnitude > 0 then md = md.Unit else md = Vector3.zero end
        local sp = s.flyspeed and s.flyspeedValue or 50
        local mv = md * sp * dt
        if vert == 1 then mv = mv + Vector3.new(0, sp * dt, 0) elseif vert == -1 then mv = mv + Vector3.new(0, -sp * dt, 0) end
        r.CFrame = r.CFrame + mv; r.Velocity = Vector3.zero; r.RotVelocity = Vector3.zero
    end
    if s.esp and s.espLine and r then
        local cam = Workspace.CurrentCamera
        if cam then
            local myPos, onScreen = cam:WorldToViewportPoint(r.Position)
            if not onScreen then myPos = nil end
            for _, v in ipairs(Players:GetPlayers()) do
                if v ~= p and v.Character then
                    local tr = v.Character:FindFirstChild("HumanoidRootPart")
                    if tr then
                        local tpos, vis = cam:WorldToViewportPoint(tr.Position)
                        if vis and myPos then
                            local line = espLines[v]
                            if not line then line = Drawing.new("Line") line.Thickness = 2 line.Color = Color3.fromRGB(255, 0, 0) espLines[v] = line end
                            line.Visible = true line.From = Vector2.new(myPos.X, myPos.Y) line.To = Vector2.new(tpos.X, tpos.Y)
                        elseif espLines[v] then espLines[v]:Remove(); espLines[v] = nil end
                    end
                end
            end
        end
    else for k, line in pairs(espLines) do pcall(function() line:Remove() end); espLines[k] = nil end end
end)
