local p = game:GetService("Players").LocalPlayer
local Players = game:GetService("Players")
local U = game:GetService("UserInputService")
local R = game:GetService("RunService")
local TS = game:GetService("TeleportService")
local Workspace = game:GetService("Workspace")
local Camera = Workspace.CurrentCamera
local g = Instance.new("ScreenGui", p:WaitForChild("PlayerGui"))
g.ResetOnSpawn = false

local lang = "cn"
local L = {
    title = {"DS通用脚本中心 v2.5", "DS Universal Script Center v2.5"},
    info = {"本脚本由DeepSeek AI生成", "Generated by DeepSeek AI"},
    close = {"关闭", "Close"},
    walkspeed = {"移动加速", "Walk Speed"},
    flyspeed = {"飞行速度", "Fly Speed"},
    gravity = {"重力调节", "Gravity"},
    noclip = {"穿墙模式", "No Clip"},
    esp = {"玩家透视", "Player ESP"},
    esp_name = {"显示名字", "Show Name"},
    esp_hl = {"高亮玩家", "Highlight"},
    esp_line = {"绘制线", "Line"},
    fly_panel = {"开启飞行面板", "Open Fly Panel"},
    airwalk_panel = {"开启踏空面板", "Open Air Walk"},
    speed = {"速度倍率", "Speed Multiplier"},
    infjump = {"无限跳跃", "Infinite Jump"},
    server = {"服务器", "Server"},
    rejoin = {"重新加入", "Rejoin"},
    reset = {"重置人物", "Reset Character"},
    player_cat = {"人物", "Player"},
    fly_air_cat = {"飞行与踏空", "Fly & Air Walk"},
    combat_cat = {"战斗模块", "Combat Module"},
    combat_load = {"加载枪战脚本", "Load Gun Script"},
    combat_unload = {"卸载枪战脚本", "Unload Gun Script"},
    on_ = {"开", "ON"},
    off = {"关", "OFF"},
    fly_title = {"ds飞行", "ds Fly"},
    fly_start = {"开启飞行", "Start Fly"},
    fly_stop = {"关闭飞行", "Stop Fly"},
    fly_up = {"▲ 向上飞", "▲ Fly Up"},
    fly_down = {"▼ 向下飞", "▼ Fly Down"},
    air_title = {"ds踏空", "ds Air Walk"},
    air_start = {"开启踏空", "Start Air Walk"},
    air_stop = {"关闭踏空", "Stop Air Walk"},
    -- 战斗模块翻译
    combat_title = {"DS枪战脚本", "DS Gun Script"},
    aim_section = {"自瞄设置", "Aimbot"},
    aim_toggle = {"开启自瞄", "Enable Aimbot"},
    part_head = {"锁定：头部", "Target: Head"},
    part_body = {"锁定：身体", "Target: Body"},
    obst_check = {"障碍检测", "Wall Check"},
    team_check = {"队伍检测", "Team Check"},
    smooth = {"平滑度", "Smoothness"},
    aim_radius = {"范围半径", "Field Radius"},
    esp_section = {"绘制设置", "ESP"},
    name_esp = {"名字透视", "Name ESP"},
    highlight_esp = {"人物高亮", "Highlight"},
    player_section = {"人物增强", "Movement"},
    speed_toggle = {"移动加速", "Speed Boost"},
    speed_val = {"加速值", "Speed Value"},
    noclip_toggle = {"穿墙模式", "No Clip"},
    fov_label = {"广角", "FOV"},
    fov_slider = {"广角度数", "FOV"},
    hitbox_section = {"碰撞箱", "Hitbox"},
    hitbox_toggle = {"修改碰撞箱", "Expand Hitboxes"},
    hitbox_mul = {"碰撞倍数", "Multiplier"},
}
local function T(key)
    local t = L[key]
    return t and t[lang == "cn" and 1 or 2] or key
end

-- 语言刷新管理
local langObjs = {}
local toggleBtns = {}
local function reg(o, k) table.insert(langObjs, {o = o, k = k}) o.Text = T(k) end
local function applyLang()
    for _, v in ipairs(langObjs) do v.o.Text = T(v.k) end
    for _, v in ipairs(toggleBtns) do
        v.btn.Text = T(v.state and "on_" or "off")
        v.btn.BackgroundColor3 = v.state and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35)
    end
    if combatLoaded then updateCombatLang() end
end
local function playSound()
    pcall(function()
        local s = Instance.new("Sound", g)
        s.SoundId = "rbxassetid://9119260689"
        s.Volume = 0.5 s:Play()
        game:GetService("Debris"):AddItem(s, 2)
    end)
end

-- 主窗口框架（固定大小，可滚动内容）
local m = Instance.new("Frame", g)
m.BackgroundColor3 = Color3.fromRGB(24, 24, 24)
m.Size = UDim2.new(0, 300, 0, 480) -- 固定高度
m.Position = UDim2.new(0.5, -150, 0.1, 0)
m.BorderSizePixel = 0
m.ClipsDescendants = true
Instance.new("UICorner", m).CornerRadius = UDim.new(0, 10)
local mainStroke = Instance.new("UIStroke", m)
mainStroke.Thickness = 2
mainStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border

-- 标题栏（固定在顶部）
local t = Instance.new("Frame", m)
t.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
t.Size = UDim2.new(1, -20, 0, 40)
t.Position = UDim2.new(0, 10, 0, 5)
t.BorderSizePixel = 0
Instance.new("UICorner", t).CornerRadius = UDim.new(0, 8)
local dr = Instance.new("TextButton", t)
dr.BackgroundTransparency = 1 dr.Size = UDim2.new(1, 0, 1, 0) dr.Text = "" dr.ZIndex = 0
local ti = Instance.new("TextButton", t)
ti.TextColor3 = Color3.fromRGB(255, 255, 255) ti.BackgroundTransparency = 1
ti.Size = UDim2.new(0, 160, 1, 0) ti.Position = UDim2.new(0, 8, 0, 0)
ti.Font = Enum.Font.GothamBold ti.TextSize = 15 ti.TextXAlignment = Enum.TextXAlignment.Left ti.ZIndex = 2
reg(ti, "title")
local langBtn = Instance.new("TextButton", t) langBtn.Text = "EN"
langBtn.TextColor3 = Color3.fromRGB(255, 255, 255) langBtn.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
langBtn.Font = Enum.Font.GothamBold langBtn.TextSize = 12 langBtn.Size = UDim2.new(0, 28, 0, 28)
langBtn.Position = UDim2.new(1, -105, 0.5, -14) langBtn.ZIndex = 2 langBtn.BorderSizePixel = 0
Instance.new("UICorner", langBtn).CornerRadius = UDim.new(0, 4)
langBtn.MouseButton1Click:Connect(function()
    lang = lang == "cn" and "en" or "cn"
    langBtn.Text = lang == "cn" and "EN" or "中"
    applyLang()
end)
local minB = Instance.new("TextButton", t) minB.Text = "—"
minB.TextColor3 = Color3.fromRGB(255, 255, 255) minB.BackgroundColor3 = Color3.fromRGB(55, 55, 55)
minB.Font = Enum.Font.GothamBold minB.TextSize = 16 minB.Size = UDim2.new(0, 30, 0, 28)
minB.Position = UDim2.new(1, -70, 0.5, -14) minB.ZIndex = 2 minB.BorderSizePixel = 0
Instance.new("UICorner", minB).CornerRadius = UDim.new(0, 4)
local clsB = Instance.new("TextButton", t) clsB.Text = "✕"
clsB.TextColor3 = Color3.fromRGB(255, 255, 255) clsB.BackgroundColor3 = Color3.fromRGB(180, 50, 50)
clsB.Font = Enum.Font.GothamBold clsB.TextSize = 14 clsB.Size = UDim2.new(0, 30, 0, 28)
clsB.Position = UDim2.new(1, -34, 0.5, -14) clsB.ZIndex = 2 clsB.BorderSizePixel = 0
Instance.new("UICorner", clsB).CornerRadius = UDim.new(0, 4)
clsB.MouseButton1Click:Connect(function()
    unloadCombatScript()
    g:Destroy()
end) -- 修复关闭按钮

-- 信息提示（在标题栏内）
local inf = Instance.new("Frame", t) inf.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
inf.Size = UDim2.new(0, 240, 0, 64) inf.Position = UDim2.new(0, 10, 1, 6) inf.Visible = false inf.ZIndex = 10
inf.BorderSizePixel = 0 Instance.new("UICorner", inf).CornerRadius = UDim.new(0, 6)
Instance.new("UIStroke", inf).Color = Color3.fromRGB(80, 80, 80)
local itx = Instance.new("TextLabel", inf) itx.TextColor3 = Color3.fromRGB(230, 230, 230) itx.BackgroundTransparency = 1
itx.Size = UDim2.new(1, -16, 0, 36) itx.Position = UDim2.new(0, 8, 0, 8) itx.Font = Enum.Font.GothamMedium
itx.TextSize = 14 itx.TextWrapped = true itx.ZIndex = 10 reg(itx, "info")
local cib = Instance.new("TextButton", inf) cib.TextColor3 = Color3.fromRGB(255, 255, 255) cib.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
cib.Font = Enum.Font.GothamBold cib.TextSize = 12 cib.Size = UDim2.new(0, 46, 0, 22) cib.Position = UDim2.new(1, -54, 1, -28)
cib.ZIndex = 11 cib.BorderSizePixel = 0 Instance.new("UICorner", cib).CornerRadius = UDim.new(0, 4) reg(cib, "close")
ti.MouseButton1Click:Connect(function()
    inf.Visible = not inf.Visible
end)
cib.MouseButton1Click:Connect(function()
    inf.Visible = false
end)

-- 最小化按钮
local mRest = Instance.new("TextButton", g) mRest.Text = "DS" mRest.TextColor3 = Color3.fromRGB(255, 255, 255)
mRest.BackgroundColor3 = Color3.fromRGB(35, 35, 35) mRest.Font = Enum.Font.GothamBold mRest.TextSize = 14
mRest.Size = UDim2.new(0, 44, 0, 44) mRest.Position = UDim2.new(1, -54, 0.5, -22) mRest.Visible = false mRest.BorderSizePixel = 0
Instance.new("UICorner", mRest).CornerRadius = UDim.new(1, 0)
minB.MouseButton1Click:Connect(function()
    m.Visible = false
    mRest.Visible = true
end)
mRest.MouseButton1Click:Connect(function()
    m.Visible = true
    mRest.Visible = false
end)

-- 可滚动内容区域
local scroll = Instance.new("ScrollingFrame", m)
scroll.Size = UDim2.new(1, -4, 1, -50) -- 减去标题栏高度
scroll.Position = UDim2.new(0, 2, 0, 48)
scroll.BackgroundTransparency = 1
scroll.BorderSizePixel = 0
scroll.ScrollBarThickness = 4
scroll.CanvasSize = UDim2.new(0, 0, 0, 0) -- 后续动态更新
scroll.ScrollBarImageColor3 = Color3.fromRGB(100, 100, 100)

local content = Instance.new("Frame", scroll)
content.BackgroundTransparency = 1
content.Size = UDim2.new(1, 0, 0, 0)
content.AutomaticSize = Enum.AutomaticSize.Y
local contentList = Instance.new("UIListLayout", content)
contentList.Padding = UDim.new(0, 8)
contentList.HorizontalAlignment = Enum.HorizontalAlignment.Center
contentList.SortOrder = Enum.SortOrder.LayoutOrder

-- 拖动窗口（标题栏）
local drag, ds, fs = false, nil, nil
dr.InputBegan:Connect(function(inp)
    if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then
        drag = true; ds = inp.Position; fs = m.Position
        inp.Changed:Connect(function()
            if inp.UserInputState == Enum.UserInputState.End then drag = false; ds = nil; fs = nil end
        end)
    end
end)
U.InputChanged:Connect(function(inp)
    if drag and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then
        local d = inp.Position - ds
        m.Position = UDim2.new(fs.X.Scale, fs.X.Offset + d.X, fs.Y.Scale, fs.Y.Offset + d.Y)
    end
end)

-- 滚动区域尺寸更新
local function updateCanvas()
    scroll.CanvasSize = UDim2.new(0, 0, 0, contentList.AbsoluteContentSize.Y + 10)
end
contentList:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(updateCanvas)

-- State
local s = {
    walkspeed = false, walkspeedValue = 50,
    flyspeed = true, flyspeedValue = 50,
    gravity = false, gravityValue = 1,
    noclip = false,
    esp = false, espShowName = true, espHighlight = true, espLine = false,
    speedMultiplier = false, speedMultiplierValue = 2,
    infiniteJump = false,
}

-- ESP 主脚本部分
local eb, eh, ec = {}, {}, {}
local espLines = {}
local function uesp(pl) pcall(function()
    local ch = pl.Character if not ch or pl == p then return end
    if eb[pl] then eb[pl]:Destroy() end if eh[pl] then eh[pl]:Destroy() end eb[pl] = nil; eh[pl] = nil
    if s.esp and s.espShowName then
        local rp = ch:FindFirstChild("HumanoidRootPart")
        if rp then
            local b = Instance.new("BillboardGui", ch) b.Adornee = rp; b.Size = UDim2.new(0, 100, 0, 40); b.StudsOffset = Vector3.new(0, 3, 0); b.AlwaysOnTop = true
            local la = Instance.new("TextLabel", b) la.Size = UDim2.new(1, 0, 1, 0); la.BackgroundTransparency = 1; la.TextColor3 = Color3.fromRGB(0, 255, 0); la.TextStrokeTransparency = 0; la.TextStrokeColor3 = Color3.fromRGB(0, 0, 0); la.Text = pl.Name; la.Font = Enum.Font.GothamBold; la.TextSize = 14; la.TextScaled = true; la.BorderSizePixel = 0
            eb[pl] = b
        end
    end
    if s.esp and s.espHighlight then
        local hl = Instance.new("Highlight", ch) hl.FillColor = Color3.fromRGB(255, 255, 0); hl.OutlineColor = Color3.fromRGB(255, 255, 255); hl.FillTransparency = 0.5
        eh[pl] = hl
    end
end) end
local function aesp(pl) if pl == p then return end if ec[pl] then ec[pl]:Disconnect() end uesp(pl) ec[pl] = pl.CharacterAdded:Connect(function() uesp(pl) end) end
local function resp(pl)
    if ec[pl] then ec[pl]:Disconnect(); ec[pl] = nil end
    if eb[pl] then eb[pl]:Destroy(); eb[pl] = nil end
    if eh[pl] then eh[pl]:Destroy(); eh[pl] = nil end
    if espLines[pl] then pcall(function() espLines[pl]:Remove() end); espLines[pl] = nil end
end
local function raesp() for _, v in ipairs(Players:GetPlayers()) do if v ~= p then uesp(v) end end end
Players.PlayerAdded:Connect(function(pl) if s.esp and pl ~= p then aesp(pl) end end)
Players.PlayerRemoving:Connect(resp)

-- UI 构造辅助（改为添加到 content 面板）
local function adjRow(key, stateKey, def, ord, parent, noToggle)
    parent = parent or content -- 改为 content
    local r = Instance.new("Frame", parent) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    r.Size = UDim2.new(1, -20, 0, 44) r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local lb = Instance.new("TextLabel", r) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1
    lb.Size = UDim2.new(0, 75, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left
    reg(lb, key)
    local vb = Instance.new("TextBox", r) vb.Text = tostring(def) vb.BackgroundColor3 = Color3.fromRGB(50, 50, 50) vb.TextColor3 = Color3.fromRGB(255, 255, 255) vb.Font = Enum.Font.GothamMedium vb.TextSize = 13
    vb.Size = UDim2.new(0, 48, 0, 26) vb.Position = UDim2.new(0, 90, 0.5, -13) vb.ClearTextOnFocus = false vb.BorderSizePixel = 0
    Instance.new("UICorner", vb).CornerRadius = UDim.new(0, 4)
    local function readValue()
        local n = tonumber(vb.Text) if n and n > 0 then s[stateKey .. "Value"] = n else vb.Text = tostring(s[stateKey .. "Value"]) end
    end
    vb:GetPropertyChangedSignal("Text"):Connect(function() local n = tonumber(vb.Text) if n and n > 0 then s[stateKey .. "Value"] = n end end)
    vb.FocusLost:Connect(readValue)
    if not noToggle then
        local tb = Instance.new("TextButton", r) tb.BackgroundColor3 = Color3.fromRGB(180, 35, 35) tb.TextColor3 = Color3.fromRGB(255, 255, 255) tb.Font = Enum.Font.GothamBold tb.TextSize = 13
        tb.Size = UDim2.new(0, 50, 0, 28) tb.Position = UDim2.new(1, -58, 0.5, -14) tb.BorderSizePixel = 0
        Instance.new("UICorner", tb).CornerRadius = UDim.new(0, 6)
        local state = false table.insert(toggleBtns, {btn = tb, state = state})
        local function uv(a) tb.Text = T(a and "on_" or "off") tb.BackgroundColor3 = a and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35) end
        tb.MouseButton1Click:Connect(function()
            readValue() s[stateKey] = not s[stateKey] state = s[stateKey] uv(state) playSound()
        end)
        s[stateKey .. "Value"] = def
    end
end

local function toggleRow(key, stateKey, ord, parent)
    parent = parent or content
    local r = Instance.new("Frame", parent) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    r.Size = UDim2.new(1, -20, 0, 44) r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local lb = Instance.new("TextLabel", r) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1
    lb.Size = UDim2.new(1, -70, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left
    reg(lb, key)
    local tb = Instance.new("TextButton", r) tb.BackgroundColor3 = Color3.fromRGB(180, 35, 35) tb.TextColor3 = Color3.fromRGB(255, 255, 255) tb.Font = Enum.Font.GothamBold tb.TextSize = 13
    tb.Size = UDim2.new(0, 50, 0, 28) tb.Position = UDim2.new(1, -58, 0.5, -14) tb.BorderSizePixel = 0
    Instance.new("UICorner", tb).CornerRadius = UDim.new(0, 6)
    local st = false table.insert(toggleBtns, {btn = tb, state = st})
    tb.MouseButton1Click:Connect(function()
        s[stateKey] = not s[stateKey] st = s[stateKey]
        tb.Text = T(st and "on_" or "off") tb.BackgroundColor3 = st and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35) playSound()
        if stateKey == "noclip" and not st and p.Character then for _, v in ipairs(p.Character:GetDescendants()) do if v:IsA("BasePart") then v.CanCollide = true end end end
    end)
end

-- 分类折叠（使用 content 作为父级）
local function categoryRow(titleKey, ord)
    local r = Instance.new("Frame", content) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 0) r.AutomaticSize = Enum.AutomaticSize.Y r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local rl = Instance.new("UIListLayout", r) rl.Padding = UDim.new(0, 4) rl.HorizontalAlignment = Enum.HorizontalAlignment.Center rl.SortOrder = Enum.SortOrder.LayoutOrder
    local top = Instance.new("Frame", r) top.BackgroundTransparency = 1 top.Size = UDim2.new(1, 0, 0, 44) top.LayoutOrder = 0
    local lb = Instance.new("TextLabel", top) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1 lb.Size = UDim2.new(1, -80, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left reg(lb, titleKey)
    local ex = Instance.new("TextButton", top) ex.Text = "▼" ex.BackgroundColor3 = Color3.fromRGB(55, 55, 55) ex.TextColor3 = Color3.fromRGB(255, 255, 255) ex.Font = Enum.Font.GothamBold ex.TextSize = 12 ex.Size = UDim2.new(0, 28, 0, 28) ex.Position = UDim2.new(1, -36, 0.5, -14) ex.BorderSizePixel = 0 Instance.new("UICorner", ex).CornerRadius = UDim.new(0, 4)
    local sf = Instance.new("Frame", r) sf.BackgroundTransparency = 1 sf.Size = UDim2.new(1, -16, 0, 0) sf.AutomaticSize = Enum.AutomaticSize.Y sf.Visible = false sf.LayoutOrder = 1
    local sl = Instance.new("UIListLayout", sf) sl.Padding = UDim.new(0, 4) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.SortOrder = Enum.SortOrder.LayoutOrder
    local exp = false
    ex.MouseButton1Click:Connect(function() exp = not exp; ex.Text = exp and "▲" or "▼"; sf.Visible = exp end)
    return sf
end

-- 人物分类
local playerCat = categoryRow("player_cat", 1)
adjRow("walkspeed", "walkspeed", 50, 1, playerCat)
toggleRow("infjump", "infiniteJump", 2, playerCat)
adjRow("gravity", "gravity", 1, 3, playerCat)
toggleRow("noclip", "noclip", 4, playerCat)
adjRow("speed", "speedMultiplier", 2.0, 5, playerCat)

-- 飞行分类
local flyAirCat = categoryRow("fly_air_cat", 2)
adjRow("flyspeed", "flyspeed", 50, 1, flyAirCat, true)
local flyBtn = Instance.new("TextButton", Instance.new("Frame", flyAirCat))
flyBtn.Parent.Size = UDim2.new(1, -20, 0, 44); flyBtn.Parent.LayoutOrder = 2; flyBtn.Parent.BackgroundColor3 = Color3.fromRGB(35, 35, 35); flyBtn.Parent.BorderSizePixel = 0
Instance.new("UICorner", flyBtn.Parent).CornerRadius = UDim.new(0, 8)
flyBtn.TextColor3 = Color3.fromRGB(255, 255, 255) flyBtn.BackgroundColor3 = Color3.fromRGB(40, 130, 220) flyBtn.Font = Enum.Font.GothamBold flyBtn.TextSize = 14 flyBtn.Size = UDim2.new(1, -16, 0, 34) flyBtn.Position = UDim2.new(0, 8, 0.5, -17) flyBtn.BorderSizePixel = 0
Instance.new("UICorner", flyBtn).CornerRadius = UDim.new(0, 6) reg(flyBtn, "fly_panel")
flyBtn.MouseButton1Click:Connect(function() if flyW then destroyFly() else showFly() end end)
local airBtn = Instance.new("TextButton", Instance.new("Frame", flyAirCat))
airBtn.Parent.Size = UDim2.new(1, -20, 0, 44); airBtn.Parent.LayoutOrder = 3; airBtn.Parent.BackgroundColor3 = Color3.fromRGB(35, 35, 35); airBtn.Parent.BorderSizePixel = 0
Instance.new("UICorner", airBtn.Parent).CornerRadius = UDim.new(0, 8)
airBtn.TextColor3 = Color3.fromRGB(255, 255, 255) airBtn.BackgroundColor3 = Color3.fromRGB(40, 130, 220) airBtn.Font = Enum.Font.GothamBold airBtn.TextSize = 14 airBtn.Size = UDim2.new(1, -16, 0, 34) airBtn.Position = UDim2.new(0, 8, 0.5, -17) airBtn.BorderSizePixel = 0
Instance.new("UICorner", airBtn).CornerRadius = UDim.new(0, 6) reg(airBtn, "airwalk_panel")
airBtn.MouseButton1Click:Connect(function() if airW then destroyAirWalk() else showAirWalk() end end)

-- 飞行/踏空面板（保持独立，仍添加到 g 中）
local flyActive, vert, flyW, flyRest, flyStroke = false, 0, nil, nil, nil
local function destroyFly()
    flyActive, vert = false, 0
    if flyW then flyW:Destroy(); flyW = nil end
    if flyRest then flyRest:Destroy(); flyRest = nil end flyStroke = nil
    local ch = p.Character if ch then local h = ch:FindFirstChildOfClass("Humanoid") if h then h.PlatformStand = false end end
end
local function showFly()
    if flyW then return end
    flyW = Instance.new("Frame", g) flyW.BackgroundColor3 = Color3.fromRGB(28, 28, 28) flyW.Size = UDim2.new(0, 210, 0, 210)
    flyW.Position = UDim2.new(0.5, -105, 0.3, 0) flyW.BorderSizePixel = 0 Instance.new("UICorner", flyW).CornerRadius = UDim.new(0, 8)
    flyStroke = Instance.new("UIStroke", flyW) flyStroke.Thickness = 2 flyStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    local ft = Instance.new("Frame", flyW) ft.BackgroundColor3 = Color3.fromRGB(38, 38, 38) ft.Size = UDim2.new(1, -16, 0, 36) ft.Position = UDim2.new(0, 8, 0, 6) ft.BorderSizePixel = 0
    Instance.new("UICorner", ft).CornerRadius = UDim.new(0, 6)
    local fti = Instance.new("TextLabel", ft) fti.TextColor3 = Color3.fromRGB(255, 255, 255) fti.BackgroundTransparency = 1 fti.Size = UDim2.new(1, -60, 1, 0) fti.Position = UDim2.new(0, 10, 0, 0) fti.Font = Enum.Font.GothamBold fti.TextSize = 16 fti.TextXAlignment = Enum.TextXAlignment.Left
    reg(fti, "fly_title")
    local fmin = Instance.new("TextButton", ft) fmin.Text = "—" fmin.TextColor3 = Color3.fromRGB(255, 255, 255) fmin.BackgroundColor3 = Color3.fromRGB(55, 55, 55) fmin.Font = Enum.Font.GothamBold fmin.TextSize = 16 fmin.Size = UDim2.new(0, 28, 0, 28) fmin.Position = UDim2.new(1, -58, 0.5, -14) fmin.BorderSizePixel = 0
    Instance.new("UICorner", fmin).CornerRadius = UDim.new(0, 4)
    local fcls = Instance.new("TextButton", ft) fcls.Text = "✕" fcls.TextColor3 = Color3.fromRGB(255, 255, 255) fcls.BackgroundColor3 = Color3.fromRGB(180, 50, 50) fcls.Font = Enum.Font.GothamBold fcls.TextSize = 14 fcls.Size = UDim2.new(0, 28, 0, 28) fcls.Position = UDim2.new(1, -28, 0.5, -14) fcls.BorderSizePixel = 0
    Instance.new("UICorner", fcls).CornerRadius = UDim.new(0, 4)
    local fdr = Instance.new("TextButton", ft) fdr.BackgroundTransparency = 1 fdr.Size = UDim2.new(1, 0, 1, 0) fdr.Text = "" fdr.ZIndex = 0
    local fdrg, fds, ffs = false, nil, nil fdr.InputBegan:Connect(function(inp) if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then fdrg = true; fds = inp.Position; ffs = flyW.Position inp.Changed:Connect(function() if inp.UserInputState == Enum.UserInputState.End then fdrg = false end end) end end)
    U.InputChanged:Connect(function(inp) if fdrg and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then local d = inp.Position - fds flyW.Position = UDim2.new(ffs.X.Scale, ffs.X.Offset + d.X, ffs.Y.Scale, ffs.Y.Offset + d.Y) end end)
    local flyToggle = Instance.new("TextButton", flyW) flyToggle.TextColor3 = Color3.fromRGB(255, 255, 255) flyToggle.BackgroundColor3 = Color3.fromRGB(40, 130, 220) flyToggle.Font = Enum.Font.GothamBold flyToggle.TextSize = 14 flyToggle.Size = UDim2.new(1, -40, 0, 36) flyToggle.Position = UDim2.new(0, 20, 0, 54) flyToggle.BorderSizePixel = 0
    Instance.new("UICorner", flyToggle).CornerRadius = UDim.new(0, 6) reg(flyToggle, "fly_start")
    local up = Instance.new("TextButton", flyW) up.TextColor3 = Color3.fromRGB(255, 255, 255) up.BackgroundColor3 = Color3.fromRGB(40, 140, 40) up.Font = Enum.Font.GothamBold up.TextSize = 16 up.Size = UDim2.new(1, -40, 0, 40) up.Position = UDim2.new(0, 20, 0, 102) up.BorderSizePixel = 0
    Instance.new("UICorner", up).CornerRadius = UDim.new(0, 6) reg(up, "fly_up")
    local dn = Instance.new("TextButton", flyW) dn.TextColor3 = Color3.fromRGB(255, 255, 255) dn.BackgroundColor3 = Color3.fromRGB(40, 100, 180) dn.Font = Enum.Font.GothamBold dn.TextSize = 16 dn.Size = UDim2.new(1, -40, 0, 40) dn.Position = UDim2.new(0, 20, 0, 152) dn.BorderSizePixel = 0
    Instance.new("UICorner", dn).CornerRadius = UDim.new(0, 6) reg(dn, "fly_down")
    flyToggle.MouseButton1Click:Connect(function() flyActive = not flyActive flyToggle.Text = T(flyActive and "fly_stop" or "fly_start") flyToggle.BackgroundColor3 = flyActive and Color3.fromRGB(180, 50, 50) or Color3.fromRGB(40, 130, 220) playSound() if not flyActive then vert = 0 end end)
    up.MouseButton1Down:Connect(function() if flyActive then vert = 1 end end) up.MouseButton1Up:Connect(function() if vert == 1 then vert = 0 end end) up.MouseLeave:Connect(function() if vert == 1 then vert = 0 end end)
    dn.MouseButton1Down:Connect(function() if flyActive then vert = -1 end end) dn.MouseButton1Up:Connect(function() if vert == -1 then vert = 0 end end) dn.MouseLeave:Connect(function() if vert == -1 then vert = 0 end end)
    flyRest = Instance.new("TextButton", g) flyRest.Text = "飞" flyRest.TextColor3 = Color3.fromRGB(255, 255, 255) flyRest.BackgroundColor3 = Color3.fromRGB(40, 130, 220) flyRest.Font = Enum.Font.GothamBold flyRest.TextSize = 16 flyRest.Size = UDim2.new(0, 44, 0, 44) flyRest.Position = UDim2.new(1, -54, 0.5, 80) flyRest.Visible = false flyRest.BorderSizePixel = 0 Instance.new("UICorner", flyRest).CornerRadius = UDim.new(1, 0)
    fmin.MouseButton1Click:Connect(function() flyW.Visible = false; flyRest.Visible = true end) fcls.MouseButton1Click:Connect(function() destroyFly() end) flyRest.MouseButton1Click:Connect(function() flyW.Visible = true; flyRest.Visible = false end)
end

local airActive, shouldFloat, airBV, airHBConn, airHumanoid, airRoot = false, false, nil, nil, nil, nil
local airJumpConn, airStateConn, airCharConn, airW, airRest, airStroke = nil, nil, nil, nil, nil, nil
local function updateAirFloat()
    if not airHumanoid or not airRoot then return end
    local inAir = (airHumanoid:GetState() == Enum.HumanoidStateType.Freefall or airHumanoid:GetState() == Enum.HumanoidStateType.Jumping)
    if airActive and shouldFloat and inAir then
        if not airBV then local bv = Instance.new("BodyVelocity") bv.MaxForce = Vector3.new(math.huge, math.huge, math.huge) bv.Velocity = Vector3.zero bv.Parent = airRoot airBV = bv end
        if not airHBConn then airHBConn = R.Heartbeat:Connect(function() if airBV and airBV.Parent and airHumanoid then local moveDir = airHumanoid.MoveDirection local speed = airHumanoid.WalkSpeed airBV.Velocity = Vector3.new(moveDir.X * speed, 0, moveDir.Z * speed) end end) end
    else if airBV then airBV:Destroy(); airBV = nil end if airHBConn then airHBConn:Disconnect(); airHBConn = nil end end
end
local function enableAirWalk() airActive = true if not airJumpConn then airJumpConn = U.JumpRequest:Connect(function() if not airActive or not airHumanoid or not airRoot then return end shouldFloat = true updateAirFloat() end) end end
local function disableAirWalk() airActive = false; shouldFloat = false if airBV then airBV:Destroy(); airBV = nil end if airHBConn then airHBConn:Disconnect(); airHBConn = nil end if airJumpConn then airJumpConn:Disconnect(); airJumpConn = nil end end
local function destroyAirWalk()
    disableAirWalk() if airStateConn then airStateConn:Disconnect(); airStateConn = nil end if airCharConn then airCharConn:Disconnect(); airCharConn = nil end
    if airW then airW:Destroy(); airW = nil end if airRest then airRest:Destroy(); airRest = nil end airStroke = nil; airHumanoid = nil; airRoot = nil
end
local function showAirWalk()
    if airW then return end
    local function onCharAdded(char) airHumanoid = char:WaitForChild("Humanoid") airRoot = char:WaitForChild("HumanoidRootPart") shouldFloat = false if airStateConn then airStateConn:Disconnect() end if airHumanoid then airStateConn = airHumanoid.StateChanged:Connect(function(_, newState) if newState == Enum.HumanoidStateType.Landed or newState == Enum.HumanoidStateType.Running then shouldFloat = false end updateAirFloat() end) end end
    if p.Character then onCharAdded(p.Character) end airCharConn = p.CharacterAdded:Connect(onCharAdded)
    airW = Instance.new("Frame", g) airW.BackgroundColor3 = Color3.fromRGB(28, 28, 28) airW.Size = UDim2.new(0, 180, 0, 120) airW.Position = UDim2.new(0.5, -90, 0.3, 0) airW.BorderSizePixel = 0 Instance.new("UICorner", airW).CornerRadius = UDim.new(0, 8)
    airStroke = Instance.new("UIStroke", airW) airStroke.Thickness = 2 airStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    local at = Instance.new("Frame", airW) at.BackgroundColor3 = Color3.fromRGB(38, 38, 38) at.Size = UDim2.new(1, -16, 0, 30) at.Position = UDim2.new(0, 8, 0, 5) at.BorderSizePixel = 0 Instance.new("UICorner", at).CornerRadius = UDim.new(0, 6)
    local ati = Instance.new("TextLabel", at) ati.TextColor3 = Color3.fromRGB(255, 255, 255) ati.BackgroundTransparency = 1 ati.Size = UDim2.new(1, -50, 1, 0) ati.Position = UDim2.new(0, 8, 0, 0) ati.Font = Enum.Font.GothamBold ati.TextSize = 14 ati.TextXAlignment = Enum.TextXAlignment.Left reg(ati, "air_title")
    local amin = Instance.new("TextButton", at) amin.Text = "—" amin.TextColor3 = Color3.fromRGB(255, 255, 255) amin.BackgroundColor3 = Color3.fromRGB(55, 55, 55) amin.Font = Enum.Font.GothamBold amin.TextSize = 14 amin.Size = UDim2.new(0, 24, 0, 24) amin.Position = UDim2.new(1, -50, 0.5, -12) amin.BorderSizePixel = 0 Instance.new("UICorner", amin).CornerRadius = UDim.new(0, 4)
    local acls = Instance.new("TextButton", at) acls.Text = "✕" acls.TextColor3 = Color3.fromRGB(255, 255, 255) acls.BackgroundColor3 = Color3.fromRGB(180, 50, 50) acls.Font = Enum.Font.GothamBold acls.TextSize = 12 acls.Size = UDim2.new(0, 24, 0, 24) acls.Position = UDim2.new(1, -24, 0.5, -12) acls.BorderSizePixel = 0 Instance.new("UICorner", acls).CornerRadius = UDim.new(0, 4)
    local adr = Instance.new("TextButton", at) adr.BackgroundTransparency = 1 adr.Size = UDim2.new(1, 0, 1, 0) adr.Text = "" adr.ZIndex = 0
    local adrag, ads, afs = false, nil, nil adr.InputBegan:Connect(function(inp) if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then adrag = true; ads = inp.Position; afs = airW.Position inp.Changed:Connect(function() if inp.UserInputState == Enum.UserInputState.End then adrag = false end end) end end)
    U.InputChanged:Connect(function(inp) if adrag and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then local d = inp.Position - ads airW.Position = UDim2.new(afs.X.Scale, afs.X.Offset + d.X, afs.Y.Scale, afs.Y.Offset + d.Y) end end)
    local airToggle = Instance.new("TextButton", airW) airToggle.TextColor3 = Color3.fromRGB(255, 255, 255) airToggle.BackgroundColor3 = Color3.fromRGB(180, 35, 35) airToggle.Font = Enum.Font.GothamBold airToggle.TextSize = 14 airToggle.Size = UDim2.new(1, -40, 0, 36) airToggle.Position = UDim2.new(0, 20, 0, 48) airToggle.BorderSizePixel = 0 Instance.new("UICorner", airToggle).CornerRadius = UDim.new(0, 6) reg(airToggle, "air_start")
    airToggle.MouseButton1Click:Connect(function() if airActive then disableAirWalk() airToggle.Text = T("air_start") airToggle.BackgroundColor3 = Color3.fromRGB(180, 35, 35) else enableAirWalk() airToggle.Text = T("air_stop") airToggle.BackgroundColor3 = Color3.fromRGB(40, 130, 40) end playSound() end)
    airRest = Instance.new("TextButton", g) airRest.Text = "空" airRest.TextColor3 = Color3.fromRGB(255, 255, 255) airRest.BackgroundColor3 = Color3.fromRGB(40, 130, 220) airRest.Font = Enum.Font.GothamBold airRest.TextSize = 14 airRest.Size = UDim2.new(0, 44, 0, 44) airRest.Position = UDim2.new(1, -54, 0.5, 130) airRest.Visible = false airRest.BorderSizePixel = 0 Instance.new("UICorner", airRest).CornerRadius = UDim.new(1, 0)
    amin.MouseButton1Click:Connect(function() airW.Visible = false; airRest.Visible = true end) acls.MouseButton1Click:Connect(function() destroyAirWalk() end) airRest.MouseButton1Click:Connect(function() airW.Visible = true; airRest.Visible = false end)
end

-- ESP 分类（添加到 content）
local function espRow(ord)
    local r = Instance.new("Frame", content) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 0) r.AutomaticSize = Enum.AutomaticSize.Y r.LayoutOrder = ord r.BorderSizePixel = 0
    Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local rl = Instance.new("UIListLayout", r) rl.Padding = UDim.new(0, 4) rl.HorizontalAlignment = Enum.HorizontalAlignment.Center rl.SortOrder = Enum.SortOrder.LayoutOrder
    local top = Instance.new("Frame", r) top.BackgroundTransparency = 1 top.Size = UDim2.new(1, 0, 0, 44) top.LayoutOrder = 0
    local lb = Instance.new("TextLabel", top) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1 lb.Size = UDim2.new(0, 75, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left reg(lb, "esp")
    local ex = Instance.new("TextButton", top) ex.Text = "▼" ex.BackgroundColor3 = Color3.fromRGB(55, 55, 55) ex.TextColor3 = Color3.fromRGB(255, 255, 255) ex.Font = Enum.Font.GothamBold ex.TextSize = 12 ex.Size = UDim2.new(0, 28, 0, 28) ex.Position = UDim2.new(0, 92, 0.5, -14) ex.BorderSizePixel = 0 Instance.new("UICorner", ex).CornerRadius = UDim.new(0, 4)
    local tb = Instance.new("TextButton", top) tb.BackgroundColor3 = Color3.fromRGB(180, 35, 35) tb.TextColor3 = Color3.fromRGB(255, 255, 255) tb.Font = Enum.Font.GothamBold tb.TextSize = 13 tb.Size = UDim2.new(0, 50, 0, 28) tb.Position = UDim2.new(1, -58, 0.5, -14) tb.BorderSizePixel = 0 Instance.new("UICorner", tb).CornerRadius = UDim.new(0, 6) table.insert(toggleBtns, {btn = tb, state = false})
    local sf = Instance.new("Frame", r) sf.BackgroundTransparency = 1 sf.Size = UDim2.new(1, -16, 0, 0) sf.AutomaticSize = Enum.AutomaticSize.Y sf.Visible = false sf.LayoutOrder = 1
    local sl = Instance.new("UIListLayout", sf) sl.Padding = UDim.new(0, 4) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.SortOrder = Enum.SortOrder.LayoutOrder
    local function stoggle(nm, k, so)
        local sr = Instance.new("Frame", sf) sr.BackgroundColor3 = Color3.fromRGB(40, 40, 40) sr.Size = UDim2.new(1, 0, 0, 32) sr.LayoutOrder = so sr.BorderSizePixel = 0 Instance.new("UICorner", sr).CornerRadius = UDim.new(0, 4)
        local slb = Instance.new("TextLabel", sr) slb.TextColor3 = Color3.fromRGB(200, 200, 200) slb.BackgroundTransparency = 1 slb.Size = UDim2.new(1, -60, 1, 0) slb.Font = Enum.Font.GothamMedium slb.TextSize = 12 slb.TextXAlignment = Enum.TextXAlignment.Left reg(slb, nm)
        local stb = Instance.new("TextButton", sr) stb.BackgroundColor3 = Color3.fromRGB(150, 40, 40) stb.TextColor3 = Color3.fromRGB(255, 255, 255) stb.Font = Enum.Font.GothamBold stb.TextSize = 11 stb.Size = UDim2.new(0, 42, 0, 22) stb.Position = UDim2.new(1, -50, 0.5, -11) stb.BorderSizePixel = 0 Instance.new("UICorner", stb).CornerRadius = UDim.new(0, 4)
        local st = false table.insert(toggleBtns, {btn = stb, state = st})
        local function suv(v) stb.Text = T(v and "on_" or "off") stb.BackgroundColor3 = v and Color3.fromRGB(40, 130, 40) or Color3.fromRGB(150, 40, 40) end
        stb.MouseButton1Click:Connect(function() s[k] = not s[k]; st = s[k]; suv(st); playSound() if s.esp then raesp() end end) suv(s[k])
    end
    stoggle("esp_name", "espShowName", 1); stoggle("esp_hl", "espHighlight", 2); stoggle("esp_line", "espLine", 3)
    local exp = false ex.MouseButton1Click:Connect(function() exp = not exp; ex.Text = exp and "▲" or "▼"; sf.Visible = exp end)
    local function umv(a) tb.Text = T(a and "on_" or "off") tb.BackgroundColor3 = a and Color3.fromRGB(30, 150, 30) or Color3.fromRGB(180, 35, 35) end
    tb.MouseButton1Click:Connect(function() s.esp = not s.esp; umv(s.esp); playSound() if s.esp then for _, v in ipairs(Players:GetPlayers()) do if v ~= p then aesp(v) end end else for _, v in ipairs(Players:GetPlayers()) do resp(v) end end end)
end
espRow(3)

-- 服务器分类
local function serverRow(ord)
    local r = Instance.new("Frame", content) r.BackgroundColor3 = Color3.fromRGB(35, 35, 35) r.Size = UDim2.new(1, -20, 0, 0) r.AutomaticSize = Enum.AutomaticSize.Y r.LayoutOrder = ord r.BorderSizePixel = 0 Instance.new("UICorner", r).CornerRadius = UDim.new(0, 8)
    local rl = Instance.new("UIListLayout", r) rl.Padding = UDim.new(0, 4) rl.HorizontalAlignment = Enum.HorizontalAlignment.Center rl.SortOrder = Enum.SortOrder.LayoutOrder
    local top = Instance.new("Frame", r) top.BackgroundTransparency = 1 top.Size = UDim2.new(1, 0, 0, 44) top.LayoutOrder = 0
    local lb = Instance.new("TextLabel", top) lb.TextColor3 = Color3.fromRGB(210, 210, 210) lb.BackgroundTransparency = 1 lb.Size = UDim2.new(1, -80, 1, 0) lb.Position = UDim2.new(0, 10, 0, 0) lb.Font = Enum.Font.GothamMedium lb.TextSize = 13 lb.TextXAlignment = Enum.TextXAlignment.Left reg(lb, "server")
    local ex = Instance.new("TextButton", top) ex.Text = "▼" ex.BackgroundColor3 = Color3.fromRGB(55, 55, 55) ex.TextColor3 = Color3.fromRGB(255, 255, 255) ex.Font = Enum.Font.GothamBold ex.TextSize = 12 ex.Size = UDim2.new(0, 28, 0, 28) ex.Position = UDim2.new(1, -36, 0.5, -14) ex.BorderSizePixel = 0 Instance.new("UICorner", ex).CornerRadius = UDim.new(0, 4)
    local sf = Instance.new("Frame", r) sf.BackgroundTransparency = 1 sf.Size = UDim2.new(1, -16, 0, 0) sf.AutomaticSize = Enum.AutomaticSize.Y sf.Visible = false sf.LayoutOrder = 1
    local sl = Instance.new("UIListLayout", sf) sl.Padding = UDim.new(0, 4) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.SortOrder = Enum.SortOrder.LayoutOrder
    local rejoinBtn = Instance.new("TextButton", sf) rejoinBtn.Size = UDim2.new(1, 0, 0, 32) rejoinBtn.BackgroundColor3 = Color3.fromRGB(40, 40, 40) rejoinBtn.TextColor3 = Color3.fromRGB(255, 255, 255) rejoinBtn.Font = Enum.Font.GothamBold rejoinBtn.TextSize = 13 rejoinBtn.BorderSizePixel = 0 Instance.new("UICorner", rejoinBtn).CornerRadius = UDim.new(0, 4) reg(rejoinBtn, "rejoin") rejoinBtn.MouseButton1Click:Connect(function() playSound() TS:Teleport(game.PlaceId, p) end)
    local resetBtn = Instance.new("TextButton", sf) resetBtn.Size = UDim2.new(1, 0, 0, 32) resetBtn.BackgroundColor3 = Color3.fromRGB(40, 40, 40) resetBtn.TextColor3 = Color3.fromRGB(255, 255, 255) resetBtn.Font = Enum.Font.GothamBold resetBtn.TextSize = 13 resetBtn.BorderSizePixel = 0 Instance.new("UICorner", resetBtn).CornerRadius = UDim.new(0, 4) reg(resetBtn, "reset") resetBtn.MouseButton1Click:Connect(function() playSound() if p.Character then p.Character:BreakJoints() end end)
    local exp = false ex.MouseButton1Click:Connect(function() exp = not exp; ex.Text = exp and "▲" or "▼"; sf.Visible = exp end)
end
serverRow(4)

-- ===== 战斗模块集成 =====
local combatLoaded = false
local combatGui = nil
local combatConnections = {}
local combatLangObjs = {}
local combatToggleBtns = {}

local function updateCombatLang()
    if not combatLoaded or not combatLangObjs then return end
    for _, v in ipairs(combatLangObjs) do
        if v.suffix then
            local num = v.obj.Text:match(": (.+)$")
            if num then v.obj.Text = T(v.key)..": "..num end
        else
            v.obj.Text = T(v.key)
        end
    end
    for _, v in ipairs(combatToggleBtns) do
        v.btn.Text = v.state and T("on_") or T("off")
    end
end

local function unloadCombatScript()
    if not combatLoaded then return end
    combatLoaded = false
    for _, conn in ipairs(combatConnections) do
        pcall(function() conn:Disconnect() end)
    end
    combatConnections = {}
    if combatGui then
        combatGui:Destroy()
        combatGui = nil
    end
    combatLangObjs = {}
    combatToggleBtns = {}
    Camera.FieldOfView = 70
    for _, pl in ipairs(Players:GetPlayers()) do
        if pl ~= p then resp(pl) end
    end
end

local function loadCombatScript()
    if combatLoaded then return end
    combatLoaded = true

    -- 战斗变量
    local aimbotOn = false
    local aimPart = "Head"
    local obstCheck = true
    local teamCheck = true
    local smoothVal = 0.3
    local aimRadius = 150
    local nameEsp = false
    local highlightEsp = false
    local speedOn = false
    local speedVal = 30
    local noclipOn = false
    local fovVal = 70
    local hitboxOn = false
    local hitboxMul = 2

    local hlObjs, nameTags, origSizes, adornments = {}, {}, {}, {}

    local function CGetEnemies()
        local e = {}
        for _, pl in ipairs(Players:GetPlayers()) do
            if pl ~= p and pl.Character and pl.Character:FindFirstChild("Humanoid") and pl.Character.Humanoid.Health > 0 then
                if teamCheck and pl.Team and p.Team and pl.Team == p.Team then continue end
                table.insert(e, pl.Character)
            end
        end
        return e
    end

    local function AimbotUpdate()
        if not aimbotOn then return end
        local center = Vector2.new(Camera.ViewportSize.X/2, Camera.ViewportSize.Y/2)
        local closestTarget, minDist = nil, aimRadius + 1
        for _, char in ipairs(CGetEnemies()) do
            local part = char:FindFirstChild(aimPart)
            if part then
                local sp, onScreen = Camera:WorldToScreenPoint(part.Position)
                if onScreen then
                    local d = (Vector2.new(sp.X, sp.Y) - center).Magnitude
                    if d < minDist then
                        if obstCheck then
                            local rayParams = RaycastParams.new()
                            rayParams.FilterDescendantsInstances = {p.Character, char}
                            rayParams.FilterType = Enum.RaycastFilterType.Blacklist
                            local ray = Workspace:Raycast(Camera.CFrame.Position, (part.Position - Camera.CFrame.Position).Unit * 1000, rayParams)
                            if ray and ray.Instance and not ray.Instance:IsDescendantOf(char) then continue end
                        end
                        minDist = d
                        closestTarget = part.Position
                    end
                end
            end
        end
        if closestTarget then
            Camera.CFrame = Camera.CFrame:Lerp(CFrame.new(Camera.CFrame.Position, closestTarget), smoothVal)
        end
    end

    local function RefreshESP()
        for _, v in pairs(hlObjs) do v:Destroy() end
        for _, v in pairs(nameTags) do v:Destroy() end
        hlObjs, nameTags = {}, {}
        if not (nameEsp or highlightEsp) then return end
        for _, char in ipairs(CGetEnemies()) do
            local plr = Players:GetPlayerFromCharacter(char)
            if plr then
                if nameEsp then
                    local bg = Instance.new("BillboardGui", char)
                    bg.Adornee = char:WaitForChild("Head", 5)
                    bg.Size = UDim2.new(0,100,0,30)
                    bg.StudsOffset = Vector3.new(0,3,0)
                    bg.AlwaysOnTop = true
                    local l = Instance.new("TextLabel", bg)
                    l.Size = UDim2.new(1,0,1,0)
                    l.BackgroundTransparency = 1
                    l.TextColor3 = Color3.new(1,1,1)
                    l.TextStrokeTransparency = 0
                    l.Font = Enum.Font.SourceSansBold
                    l.TextSize = 14
                    l.Text = plr.Name
                    nameTags[plr] = bg
                end
                if highlightEsp then
                    local hl = Instance.new("Highlight", combatGui)
                    hl.FillColor = Color3.fromRGB(255,100,100)
                    hl.OutlineColor = Color3.new(1,0,0)
                    hl.FillTransparency = 0.4
                    hl.OutlineTransparency = 0
                    hl.Adornee = char
                    hlObjs[plr] = hl
                end
            end
        end
    end

    local function UpdateHitboxes()
        for _, ads in pairs(adornments) do for _, a in ipairs(ads) do a:Destroy() end end
        adornments = {}
        for _, char in ipairs(CGetEnemies()) do
            local plr = Players:GetPlayerFromCharacter(char)
            if plr then
                if not origSizes[plr] then origSizes[plr] = {} end
                if not adornments[plr] then adornments[plr] = {} end
                for _, part in ipairs(char:GetDescendants()) do
                    if part:IsA("BasePart") then
                        if not origSizes[plr][part] then origSizes[plr][part] = part.Size end
                        local ns = origSizes[plr][part] * (hitboxOn and hitboxMul or 1)
                        part.Size = ns
                        if hitboxOn then
                            local ad = Instance.new("BoxHandleAdornment", combatGui)
                            ad.Adornee = part
                            ad.Size = ns
                            ad.Transparency = 0.4
                            ad.Color3 = Color3.new(0,1,0)
                            ad.AlwaysOnTop = true
                            ad.ZIndex = 1
                            table.insert(adornments[plr], ad)
                        end
                    end
                end
            end
        end
        if not hitboxOn then
            for plr, parts in pairs(origSizes) do
                for part, sz in pairs(parts) do
                    if part and part.Parent then part.Size = sz end
                end
            end
            origSizes = {}
        end
    end

    local function ApplySpeed()
        local hum = p.Character and p.Character:FindFirstChild("Humanoid")
        if hum then hum.WalkSpeed = speedOn and speedVal or 16 end
    end

    -- 心跳
    local combatHB = R.Heartbeat:Connect(function()
        AimbotUpdate()
        if noclipOn and p.Character then
            for _, part in ipairs(p.Character:GetDescendants()) do
                if part:IsA("BasePart") then part.CanCollide = false end
            end
        end
    end)
    table.insert(combatConnections, combatHB)

    local charAddedConn = p.CharacterAdded:Connect(function()
        ApplySpeed()
        RefreshESP()
        UpdateHitboxes()
    end)
    table.insert(combatConnections, charAddedConn)

    local playerAddedConn = Players.PlayerAdded:Connect(function(pl)
        pl.CharacterAdded:Connect(function() wait(0.3); RefreshESP(); UpdateHitboxes() end)
        if pl ~= p then wait(0.3); RefreshESP(); UpdateHitboxes() end
    end)
    table.insert(combatConnections, playerAddedConn)

    local playerRemovingConn = Players.PlayerRemoving:Connect(function(pl)
        if hlObjs[pl] then hlObjs[pl]:Destroy(); hlObjs[pl] = nil end
        if nameTags[pl] then nameTags[pl]:Destroy(); nameTags[pl] = nil end
        if adornments[pl] then for _, a in ipairs(adornments[pl]) do a:Destroy() end; adornments[pl] = nil end
        if origSizes[pl] then origSizes[pl] = nil end
    end)
    table.insert(combatConnections, playerRemovingConn)

    -- 战斗GUI（固定大小可滚动）
    combatGui = Instance.new("ScreenGui", g)
    local CombatMain = Instance.new("Frame", combatGui)
    CombatMain.Size = UDim2.new(0, 260, 0, 420)
    CombatMain.Position = UDim2.new(0.5, -130, 0.3, 0)
    CombatMain.BackgroundColor3 = Color3.fromRGB(30,30,30)
    CombatMain.BorderSizePixel = 0
    CombatMain.ClipsDescendants = true
    Instance.new("UICorner", CombatMain).CornerRadius = UDim.new(0, 8)

    -- 标题栏
    local cTitleBar = Instance.new("Frame", CombatMain)
    cTitleBar.Size = UDim2.new(1, -16, 0, 30)
    cTitleBar.Position = UDim2.new(0, 8, 0, 5)
    cTitleBar.BackgroundColor3 = Color3.fromRGB(40,40,40)
    cTitleBar.BorderSizePixel = 0
    Instance.new("UICorner", cTitleBar).CornerRadius = UDim.new(0, 6)
    local cTitle = Instance.new("TextLabel", cTitleBar)
    cTitle.Size = UDim2.new(1, -50, 1, 0)
    cTitle.Position = UDim2.new(0, 10, 0, 0)
    cTitle.BackgroundTransparency = 1
    cTitle.TextColor3 = Color3.new(1,1,1)
    cTitle.Font = Enum.Font.GothamBold
    cTitle.TextSize = 14
    cTitle.TextXAlignment = Enum.TextXAlignment.Left
    table.insert(combatLangObjs, {obj = cTitle, key = "combat_title"})
    -- 最小化按钮
    local cMin = Instance.new("TextButton", cTitleBar)
    cMin.Size = UDim2.new(0, 20, 0, 20)
    cMin.Position = UDim2.new(1, -50, 0.5, -10)
    cMin.BackgroundColor3 = Color3.fromRGB(55,55,55)
    cMin.TextColor3 = Color3.new(1,1,1)
    cMin.Font = Enum.Font.GothamBold
    cMin.TextSize = 14
    cMin.Text = "—"
    cMin.BorderSizePixel = 0
    Instance.new("UICorner", cMin).CornerRadius = UDim.new(0, 4)
    local cClose = Instance.new("TextButton", cTitleBar)
    cClose.Size = UDim2.new(0, 20, 0, 20)
    cClose.Position = UDim2.new(1, -25, 0.5, -10)
    cClose.BackgroundColor3 = Color3.fromRGB(200,50,50)
    cClose.TextColor3 = Color3.new(1,1,1)
    cClose.Font = Enum.Font.GothamBold
    cClose.TextSize = 14
    cClose.Text = "X"
    cClose.BorderSizePixel = 0
    Instance.new("UICorner", cClose).CornerRadius = UDim.new(0, 4)
    cClose.MouseButton1Click:Connect(function() unloadCombatScript() end)

    -- 拖动标题栏
    local cDrag = Instance.new("TextButton", cTitleBar)
    cDrag.BackgroundTransparency = 1
    cDrag.Size = UDim2.new(1, -70, 1, 0)
    cDrag.Text = ""
    cDrag.ZIndex = 0
    local cdrag, cds, cfs = false, nil, nil
    cDrag.InputBegan:Connect(function(inp)
        if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then
            cdrag = true; cds = inp.Position; cfs = CombatMain.Position
            inp.Changed:Connect(function()
                if inp.UserInputState == Enum.UserInputState.End then cdrag = false end
            end)
        end
    end)
    U.InputChanged:Connect(function(inp)
        if cdrag and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then
            local d = inp.Position - cds
            CombatMain.Position = UDim2.new(cfs.X.Scale, cfs.X.Offset + d.X, cfs.Y.Scale, cfs.Y.Offset + d.Y)
        end
    end)

    -- 战斗内容可滚动区域
    local cScroll = Instance.new("ScrollingFrame", CombatMain)
    cScroll.Size = UDim2.new(1, -4, 1, -40)
    cScroll.Position = UDim2.new(0, 2, 0, 38)
    cScroll.BackgroundTransparency = 1
    cScroll.BorderSizePixel = 0
    cScroll.ScrollBarThickness = 4
    cScroll.CanvasSize = UDim2.new(0,0,0,0)
    cScroll.ScrollBarImageColor3 = Color3.fromRGB(100,100,100)

    local cContent = Instance.new("Frame", cScroll)
    cContent.BackgroundTransparency = 1
    cContent.Size = UDim2.new(1, 0, 0, 0)
    cContent.AutomaticSize = Enum.AutomaticSize.Y
    local cContentList = Instance.new("UIListLayout", cContent)
    cContentList.Padding = UDim.new(0, 6)
    cContentList.HorizontalAlignment = Enum.HorizontalAlignment.Center
    cContentList.SortOrder = Enum.SortOrder.LayoutOrder

    local function updateCanvasC()
        cScroll.CanvasSize = UDim2.new(0, 0, 0, cContentList.AbsoluteContentSize.Y + 10)
    end
    cContentList:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(updateCanvasC)

    -- 最小化/恢复
    local cRestBtn = Instance.new("TextButton", g)
    cRestBtn.Text = "枪"
    cRestBtn.TextColor3 = Color3.fromRGB(255,255,255)
    cRestBtn.BackgroundColor3 = Color3.fromRGB(200,50,50)
    cRestBtn.Font = Enum.Font.GothamBold
    cRestBtn.TextSize = 14
    cRestBtn.Size = UDim2.new(0, 44, 0, 44)
    cRestBtn.Position = UDim2.new(1, -54, 0.5, 130)
    cRestBtn.Visible = false
    cRestBtn.BorderSizePixel = 0
    Instance.new("UICorner", cRestBtn).CornerRadius = UDim.new(1, 0)
    cMin.MouseButton1Click:Connect(function()
        CombatMain.Visible = false
        cRestBtn.Visible = true
    end)
    cRestBtn.MouseButton1Click:Connect(function()
        CombatMain.Visible = true
        cRestBtn.Visible = false
    end)

    -- 战斗UI辅助
    local combOrder = 1
    local function CAddLabel(key)
        local lbl = Instance.new("TextLabel", cContent)
        lbl.Size = UDim2.new(1, -16, 0, 18)
        lbl.BackgroundTransparency = 1
        lbl.TextColor3 = Color3.fromRGB(255,255,0)
        lbl.Font = Enum.Font.SourceSansBold
        lbl.TextSize = 12
        lbl.TextXAlignment = Enum.TextXAlignment.Left
        lbl.Text = "  "..T(key)
        lbl.LayoutOrder = combOrder; combOrder = combOrder + 1
        table.insert(combatLangObjs, {obj = lbl, key = key})
    end
    local function CAddToggle(key, default, callback)
        local f = Instance.new("Frame", cContent)
        f.Size = UDim2.new(1, -16, 0, 28)
        f.BackgroundColor3 = Color3.fromRGB(45,45,45)
        f.BorderSizePixel = 0
        f.LayoutOrder = combOrder; combOrder = combOrder + 1
        Instance.new("UICorner", f).CornerRadius = UDim.new(0, 4)
        local lb = Instance.new("TextLabel", f)
        lb.Size = UDim2.new(0.6, 0, 1, 0)
        lb.Position = UDim2.new(0.05, 0, 0, 0)
        lb.BackgroundTransparency = 1
        lb.TextColor3 = Color3.fromRGB(200,200,200)
        lb.Font = Enum.Font.SourceSans
        lb.TextSize = 12
        lb.Text = T(key)
        table.insert(combatLangObjs, {obj = lb, key = key})
        local btn = Instance.new("TextButton", f)
        btn.Size = UDim2.new(0, 42, 0, 20)
        btn.Position = UDim2.new(0.75, 0, 0.5, -10)
        btn.BorderSizePixel = 0
        btn.Text = ""
        local state = default
        local sLabel = Instance.new("TextLabel", btn)
        sLabel.Size = UDim2.new(1, 0, 1, 0)
        sLabel.BackgroundTransparency = 1
        sLabel.TextColor3 = Color3.new(1,1,1)
        sLabel.Font = Enum.Font.SourceSansBold
        sLabel.TextSize = 11
        table.insert(combatToggleBtns, {btn = sLabel, state = state})
        local function upd()
            btn.BackgroundColor3 = state and Color3.fromRGB(40,200,40) or Color3.fromRGB(200,40,40)
            sLabel.Text = state and T("on_") or T("off")
            if callback then callback(state) end
        end
        btn.MouseButton1Click:Connect(function() state = not state; upd() end)
        upd()
        return state
    end
    local function CAddSlider(key, min, max, default, callback)
        local f = Instance.new("Frame", cContent)
        f.Size = UDim2.new(1, -16, 0, 42)
        f.BackgroundColor3 = Color3.fromRGB(45,45,45)
        f.BorderSizePixel = 0
        f.LayoutOrder = combOrder; combOrder = combOrder + 1
        Instance.new("UICorner", f).CornerRadius = UDim.new(0, 4)
        local lb = Instance.new("TextLabel", f)
        lb.Size = UDim2.new(0.4, 0, 0, 18)
        lb.Position = UDim2.new(0.05, 0, 0, 2)
        lb.BackgroundTransparency = 1
        lb.TextColor3 = Color3.fromRGB(200,200,200)
        lb.Font = Enum.Font.SourceSans
        lb.TextSize = 11
        lb.Text = T(key)..": "..default
        table.insert(combatLangObjs, {obj = lb, key = key, suffix = true})
        local box = Instance.new("TextBox", f)
        box.Size = UDim2.new(0.5, 0, 0, 18)
        box.Position = UDim2.new(0.5, 0, 0, 20)
        box.BackgroundColor3 = Color3.fromRGB(70,70,70)
        box.TextColor3 = Color3.new(1,1,1)
        box.Font = Enum.Font.SourceSans
        box.TextSize = 12
        box.Text = tostring(default)
        box.FocusLost:Connect(function()
            local n = tonumber(box.Text)
            if n then n = math.clamp(n, min, max); box.Text = tostring(n); lb.Text = T(key)..": "..n; if callback then callback(n) end
            else box.Text = tostring(default) end
        end)
        return tonumber(box.Text) or default
    end

    -- 构建战斗UI
    CAddLabel("aim_section")
    local partBtn = Instance.new("TextButton", cContent)
    partBtn.Size = UDim2.new(1, -16, 0, 24)
    partBtn.BackgroundColor3 = Color3.fromRGB(70,70,70)
    partBtn.TextColor3 = Color3.new(1,1,1)
    partBtn.Font = Enum.Font.SourceSans
    partBtn.TextSize = 13
    partBtn.Text = T("part_head")
    partBtn.LayoutOrder = combOrder; combOrder = combOrder + 1
    Instance.new("UICorner", partBtn).CornerRadius = UDim.new(0, 4)
    table.insert(combatLangObjs, {obj = partBtn, key = "part_head"})
    partBtn.MouseButton1Click:Connect(function()
        aimPart = aimPart == "Head" and "HumanoidRootPart" or "Head"
        partBtn.Text = aimPart == "Head" and T("part_head") or T("part_body")
    end)
    CAddToggle("aim_toggle", false, function(v) aimbotOn = v end)
    CAddToggle("obst_check", true, function(v) obstCheck = v end)
    CAddToggle("team_check", true, function(v) teamCheck = v end)
    CAddSlider("smooth", 0.1, 1, 0.3, function(v) smoothVal = v end)
    CAddSlider("aim_radius", 50, 400, 150, function(v) aimRadius = v end)
    CAddLabel("esp_section")
    CAddToggle("name_esp", false, function(v) nameEsp = v; RefreshESP() end)
    CAddToggle("highlight_esp", false, function(v) highlightEsp = v; RefreshESP() end)
    CAddLabel("player_section")
    CAddToggle("speed_toggle", false, function(v) speedOn = v; ApplySpeed() end)
    CAddSlider("speed_val", 20, 200, 30, function(v) speedVal = v; ApplySpeed() end)
    CAddToggle("noclip_toggle", false, function(v) noclipOn = v end)
    CAddLabel("fov_label")
    CAddSlider("fov_slider", 30, 150, 70, function(v) fovVal = v; Camera.FieldOfView = v end)
    CAddLabel("hitbox_section")
    CAddToggle("hitbox_toggle", false, function(v) hitboxOn = v; UpdateHitboxes() end)
    CAddSlider("hitbox_mul", 1.1, 5, 2, function(v) hitboxMul = v; UpdateHitboxes() end)

    -- 初始化
    ApplySpeed()
    Camera.FieldOfView = fovVal
    RefreshESP()
end

-- 战斗模块分类按钮（添加到 content）
local combatCat = categoryRow("combat_cat", 5)
local combatLoadBtn = Instance.new("TextButton", Instance.new("Frame", combatCat))
combatLoadBtn.Parent.Size = UDim2.new(1, -20, 0, 44); combatLoadBtn.Parent.LayoutOrder = 1; combatLoadBtn.Parent.BackgroundColor3 = Color3.fromRGB(35, 35, 35); combatLoadBtn.Parent.BorderSizePixel = 0
Instance.new("UICorner", combatLoadBtn.Parent).CornerRadius = UDim.new(0, 8)
combatLoadBtn.TextColor3 = Color3.fromRGB(255, 255, 255) combatLoadBtn.BackgroundColor3 = Color3.fromRGB(180, 50, 50)
combatLoadBtn.Font = Enum.Font.GothamBold combatLoadBtn.TextSize = 14 combatLoadBtn.Size = UDim2.new(1, -16, 0, 34) combatLoadBtn.Position = UDim2.new(0, 8, 0.5, -17) combatLoadBtn.BorderSizePixel = 0
Instance.new("UICorner", combatLoadBtn).CornerRadius = UDim.new(0, 6)
reg(combatLoadBtn, "combat_load")
combatLoadBtn.MouseButton1Click:Connect(function()
    if combatLoaded then
        unloadCombatScript()
        combatLoadBtn.Text = T("combat_load")
        combatLoadBtn.BackgroundColor3 = Color3.fromRGB(180, 50, 50)
    else
        loadCombatScript()
        combatLoadBtn.Text = T("combat_unload")
        combatLoadBtn.BackgroundColor3 = Color3.fromRGB(40, 130, 40)
    end
    playSound()
end)

-- 无限跳跃
U.JumpRequest:Connect(function()
    if not s.infiniteJump then return end
    local c = p.Character if c then local h = c:FindFirstChildOfClass("Humanoid") if h and h:GetState() ~= Enum.HumanoidStateType.Landed then h:ChangeState(Enum.HumanoidStateType.Jumping) end end
end)

-- 主循环
local lh, dws, hue = nil, 16, 0
R.Heartbeat:Connect(function(dt)
    hue = (hue + 60 * dt) % 360
    local color = Color3.fromHSV(hue / 360, 1, 1)
    mainStroke.Color = color
    if flyStroke then flyStroke.Color = color end
    if airStroke then airStroke.Color = color end
    ti.TextColor3 = color
    local c = p.Character local h = c and c:FindFirstChildOfClass("Humanoid") local r = c and c:FindFirstChild("HumanoidRootPart")
    if h then
        if h ~= lh then dws = h.WalkSpeed; lh = h end
        if s.walkspeed then h.WalkSpeed = math.max(1, s.walkspeedValue) else h.WalkSpeed = dws end
        if s.speedMultiplier then h.WalkSpeed = h.WalkSpeed * s.speedMultiplierValue end
    else lh = nil end
    if s.gravity then Workspace.Gravity = 196.2 * s.gravityValue else Workspace.Gravity = 196.2 end
    if c and s.noclip then for _, v in ipairs(c:GetDescendants()) do if v:IsA("BasePart") then v.CanCollide = false end end end
    if flyActive and r and h then
        h.PlatformStand = true
        local md = h.MoveDirection if md.Magnitude > 0 then md = md.Unit else md = Vector3.zero end
        local sp = s.flyspeed and s.flyspeedValue or 50
        local mv = md * sp * dt
        if vert == 1 then mv = mv + Vector3.new(0, sp * dt, 0) elseif vert == -1 then mv = mv + Vector3.new(0, -sp * dt, 0) end
        r.CFrame = r.CFrame + mv; r.Velocity = Vector3.zero; r.RotVelocity = Vector3.zero
    end
    if s.esp and s.espLine and r then
        local cam = Workspace.CurrentCamera
        if cam then
            local myPos, onScreen = cam:WorldToViewportPoint(r.Position)
            if not onScreen then myPos = nil end
            for _, v in ipairs(Players:GetPlayers()) do
                if v ~= p and v.Character then
                    local tr = v.Character:FindFirstChild("HumanoidRootPart")
                    if tr thenlocal tpos, vis = cam:WorldToViewportPoint(tr.Position)
                        if vis and myPos then
                            local line = espLines[v]
                            if not line then line = Drawing.new("Line") line.Thickness = 2 line.Color = Color3.fromRGB(255, 0, 0) espLines[v] = line end
                            line.Visible = true line.From = Vector2.new(myPos.X, myPos.Y) line.To = Vector2.new(tpos.X, tpos.Y)
                        elseif espLines[v] then espLines[v]:Remove(); espLines[v] = nil end
                    end
                end
            end
        end
    else for k, line in pairs(espLines) do pcall(function() line:Remove() end); espLines[k] = nil end end
end)
